#############################################################################
# Makefile for building: larus
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  larus.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile larus.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       =
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=c++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INCPATH       = -I. 
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
LINK          = g++
LFLAGS        = -static-libstdc++ 
LIBS          = $(SUBLIBS) 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip


####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		CLTheory/Formula.cpp \
		CLTheory/Theory.cpp \
		CLProof/CLProof.cpp \
		ProvingEngine/NewSMT_Engine/Expression.cpp \
		ProvingEngine/NewSMT_Engine/SMT_ProvingEngine.cpp \
		ProvingEngine/SMTOut.cpp \
		ProvingEngine/SMT_Engine/OldSMT_ProvingEngine.cpp \
		ProvingEngine/URSA_Engine/URSA_ProvingEngine.cpp \
		ProvingEngine/STL_Engine/STL_ProvingEngine.cpp \
		ProvingEngine/STL_Engine/STL_FactsDatabase.cpp \
		ProofExport/ProofExport2Coq.cpp \
		ProofExport/ProofExport2Isabelle.cpp \
		ProofExport/ProofExport2Mizar.cpp \
		ProofExport/ProofExport2LaTeX.cpp \
		ProofExport/ProofExport2GCLC.cpp \
		ProofExport/ProofExport2GCLC_predicates.cpp \
		common.cpp \
		import.cpp 
OBJECTS       = main.o \
		Formula.o \
		Theory.o \
		CLProof.o \
		Expression.o \
		SMT_ProvingEngine.o \
		SMTOut.o \
		OldSMT_ProvingEngine.o \
		URSA_ProvingEngine.o \
		STL_ProvingEngine.o \
		STL_FactsDatabase.o \
		ProofExport2Coq.o \
		ProofExport2Isabelle.o \
		ProofExport2Mizar.o \
		ProofExport2LaTeX.o \
		ProofExport2GCLC.o \
		ProofExport2GCLC_predicates.o \
		common.o \
		import.o
DIST          = CLTheory/Formula.h \
		CLTheory/Theory.h \
		CLProof/CLProof.h \
		ProvingEngine/FactsDatabase.h \
		ProvingEngine/NewSMT_Engine/Expression.h \
		ProvingEngine/NewSMT_Engine/SMT_ProvingEngine.h \
		ProvingEngine/ProvingEngine.h \
		ProvingEngine/SMTOut.h \
		ProvingEngine/SMT_Engine/OldSMT_ProvingEngine.h \
		ProvingEngine/URSA_Engine/URSA_ProvingEngine.h \
		ProvingEngine/STL_Engine/STL_FactsDatabase.h \
		ProvingEngine/STL_Engine/STL_ProvingEngine.h \
		ProofExport/ProofExport.h \
		ProofExport/ProofExport2Coq.h \
		ProofExport/ProofExport2Isabelle.h \
		ProofExport/ProofExport2Mizar.h \
		ProofExport/ProofExport2LaTeX.h \
		ProofExport/ProofExport2GCLC.h \
		ProofExport/ProofExport2GCLC_predicates.h \
		common.h main.cpp \
		CLTheory/Formula.cpp \
		CLTheory/Theory.cpp \
		CLProof/CLProof.cpp \
		ProvingEngine/NewSMT_Engine/Expression.cpp \
		ProvingEngine/NewSMT_Engine/SMT_ProvingEngine.cpp \
		ProvingEngine/SMTOut.cpp \
		ProvingEngine/SMT_Engine/OldSMT_ProvingEngine.cpp \
		ProvingEngine/URSA_Engine/URSA_ProvingEngine.cpp \
		ProvingEngine/STL_Engine/STL_ProvingEngine.cpp \
		ProvingEngine/STL_Engine/STL_FactsDatabase.cpp \
		ProofExport/ProofExport2Coq.cpp \
		ProofExport/ProofExport2Isabelle.cpp \
		ProofExport/ProofExport2Mizar.cpp \
		ProofExport/ProofExport2LaTeX.cpp \
		ProofExport/ProofExport2GCLC.cpp \
		ProofExport/ProofExport2GCLC_predicates.cpp \
		common.cpp \
		import.cpp
QMAKE_TARGET  = larus
DESTDIR       = 
TARGET        = larus


first: all
####### Build rules

larus:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

all: Makefile larus

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CLTheory/Formula.h CLTheory/Theory.h CLProof/CLProof.h ProvingEngine/FactsDatabase.h ProvingEngine/NewSMT_Engine/Expression.h ProvingEngine/NewSMT_Engine/SMT_ProvingEngine.h ProvingEngine/ProvingEngine.h ProvingEngine/SMTOut.h ProvingEngine/SMT_Engine/OldSMT_ProvingEngine.h ProvingEngine/URSA_Engine/URSA_ProvingEngine.h ProvingEngine/STL_Engine/STL_FactsDatabase.h ProvingEngine/STL_Engine/STL_ProvingEngine.h ProofExport/ProofExport.h ProofExport/ProofExport2Coq.h ProofExport/ProofExport2Isabelle.h ProofExport/ProofExport2Mizar.h ProofExport/ProofExport2LaTeX.h ProofExport/ProofExport2GCLC.h ProofExport/ProofExport2GCLC_predicates.h common.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp CLTheory/Formula.cpp CLTheory/Theory.cpp CLProof/CLProof.cpp ProvingEngine/NewSMT_Engine/Expression.cpp ProvingEngine/NewSMT_Engine/SMT_ProvingEngine.cpp ProvingEngine/SMTOut.cpp ProvingEngine/SMT_Engine/OldSMT_ProvingEngine.cpp ProvingEngine/URSA_Engine/URSA_ProvingEngine.cpp ProvingEngine/STL_Engine/STL_ProvingEngine.cpp ProvingEngine/STL_Engine/STL_FactsDatabase.cpp ProofExport/ProofExport2Coq.cpp ProofExport/ProofExport2Isabelle.cpp ProofExport/ProofExport2Mizar.cpp ProofExport/ProofExport2LaTeX.cpp ProofExport/ProofExport2GCLC.cpp ProofExport/ProofExport2GCLC_predicates.cpp common.cpp import.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp CLTheory/Theory.h \
		CLTheory/Formula.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Formula.o: CLTheory/Formula.cpp CLTheory/Formula.h \
		common.h \
		CLTheory/Theory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Formula.o CLTheory/Formula.cpp

Theory.o: CLTheory/Theory.cpp CLTheory/Theory.h \
		CLTheory/Formula.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Theory.o CLTheory/Theory.cpp

CLProof.o: CLProof/CLProof.cpp CLProof/CLProof.h \
		CLTheory/Formula.h \
		common.h \
		CLTheory/Theory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CLProof.o CLProof/CLProof.cpp

Expression.o: ProvingEngine/NewSMT_Engine/Expression.cpp ProvingEngine/NewSMT_Engine/Expression.h \
		common.h \
		ProvingEngine/SMTOut.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Expression.o ProvingEngine/NewSMT_Engine/Expression.cpp

SMT_ProvingEngine.o: ProvingEngine/NewSMT_Engine/SMT_ProvingEngine.cpp ProvingEngine/NewSMT_Engine/SMT_ProvingEngine.h \
		CLProof/CLProof.h \
		CLTheory/Formula.h \
		common.h \
		CLTheory/Theory.h \
		ProvingEngine/ProvingEngine.h \
		ProvingEngine/NewSMT_Engine/Expression.h \
		ProvingEngine/SMTOut.h \
		ProvingEngine/STL_Engine/STL_FactsDatabase.h \
		ProvingEngine/FactsDatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SMT_ProvingEngine.o ProvingEngine/NewSMT_Engine/SMT_ProvingEngine.cpp

SMTOut.o: ProvingEngine/SMTOut.cpp ProvingEngine/SMTOut.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SMTOut.o ProvingEngine/SMTOut.cpp

OldSMT_ProvingEngine.o: ProvingEngine/SMT_Engine/OldSMT_ProvingEngine.cpp ProvingEngine/SMT_Engine/OldSMT_ProvingEngine.h \
		CLProof/CLProof.h \
		CLTheory/Formula.h \
		common.h \
		CLTheory/Theory.h \
		ProvingEngine/ProvingEngine.h \
		ProvingEngine/STL_Engine/STL_FactsDatabase.h \
		ProvingEngine/FactsDatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OldSMT_ProvingEngine.o ProvingEngine/SMT_Engine/OldSMT_ProvingEngine.cpp

URSA_ProvingEngine.o: ProvingEngine/URSA_Engine/URSA_ProvingEngine.cpp ProvingEngine/URSA_Engine/URSA_ProvingEngine.h \
		common.h \
		CLTheory/Theory.h \
		CLTheory/Formula.h \
		CLProof/CLProof.h \
		ProvingEngine/ProvingEngine.h \
		ProvingEngine/STL_Engine/STL_FactsDatabase.h \
		ProvingEngine/FactsDatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o URSA_ProvingEngine.o ProvingEngine/URSA_Engine/URSA_ProvingEngine.cpp

STL_ProvingEngine.o: ProvingEngine/STL_Engine/STL_ProvingEngine.cpp ProvingEngine/STL_Engine/STL_ProvingEngine.h \
		CLProof/CLProof.h \
		CLTheory/Formula.h \
		common.h \
		CLTheory/Theory.h \
		ProvingEngine/ProvingEngine.h \
		ProvingEngine/STL_Engine/STL_FactsDatabase.h \
		ProvingEngine/FactsDatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o STL_ProvingEngine.o ProvingEngine/STL_Engine/STL_ProvingEngine.cpp

STL_FactsDatabase.o: ProvingEngine/STL_Engine/STL_FactsDatabase.cpp ProvingEngine/STL_Engine/STL_FactsDatabase.h \
		CLTheory/Formula.h \
		common.h \
		CLTheory/Theory.h \
		ProvingEngine/FactsDatabase.h \
		CLProof/CLProof.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o STL_FactsDatabase.o ProvingEngine/STL_Engine/STL_FactsDatabase.cpp

ProofExport2Coq.o: ProofExport/ProofExport2Coq.cpp ProofExport/ProofExport2Coq.h \
		ProofExport/ProofExport.h \
		common.h \
		CLProof/CLProof.h \
		CLTheory/Formula.h \
		CLTheory/Theory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProofExport2Coq.o ProofExport/ProofExport2Coq.cpp

ProofExport2Isabelle.o: ProofExport/ProofExport2Isabelle.cpp ProofExport/ProofExport2Isabelle.h \
		ProofExport/ProofExport.h \
		common.h \
		CLProof/CLProof.h \
		CLTheory/Formula.h \
		CLTheory/Theory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProofExport2Isabelle.o ProofExport/ProofExport2Isabelle.cpp

ProofExport2Mizar.o: ProofExport/ProofExport2Mizar.cpp ProofExport/ProofExport2Mizar.h \
		ProofExport/ProofExport.h \
		common.h \
		CLProof/CLProof.h \
		CLTheory/Formula.h \
		CLTheory/Theory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProofExport2Mizar.o ProofExport/ProofExport2Mizar.cpp

ProofExport2LaTeX.o: ProofExport/ProofExport2LaTeX.cpp ProofExport/ProofExport2LaTeX.h \
		ProofExport/ProofExport.h \
		common.h \
		CLProof/CLProof.h \
		CLTheory/Formula.h \
		CLTheory/Theory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProofExport2LaTeX.o ProofExport/ProofExport2LaTeX.cpp

ProofExport2GCLC.o: ProofExport/ProofExport2GCLC.cpp ProofExport/ProofExport2GCLC.h \
		ProofExport/ProofExport.h \
		common.h \
		CLProof/CLProof.h \
		CLTheory/Formula.h \
		CLTheory/Theory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProofExport2GCLC.o ProofExport/ProofExport2GCLC.cpp

ProofExport2GCLC_predicates.o: ProofExport/ProofExport2GCLC_predicates.cpp ProofExport/ProofExport2GCLC_predicates.h \
		ProofExport/ProofExport.h \
		common.h \
		CLProof/CLProof.h \
		CLTheory/Formula.h \
		CLTheory/Theory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProofExport2GCLC_predicates.o ProofExport/ProofExport2GCLC_predicates.cpp

common.o: common.cpp common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o common.o common.cpp

import.o: import.cpp CLTheory/Formula.h \
		common.h \
		CLTheory/Theory.h \
		ProofExport/ProofExport.h \
		CLProof/CLProof.h \
		ProofExport/ProofExport2Coq.h \
		ProofExport/ProofExport2Mizar.h \
		ProofExport/ProofExport2GCLC.h \
		ProofExport/ProofExport2GCLC_predicates.h \
		ProofExport/ProofExport2Isabelle.h \
		ProofExport/ProofExport2LaTeX.h \
		ProvingEngine/SMT_Engine/OldSMT_ProvingEngine.h \
		ProvingEngine/ProvingEngine.h \
		ProvingEngine/STL_Engine/STL_ProvingEngine.h \
		ProvingEngine/STL_Engine/STL_FactsDatabase.h \
		ProvingEngine/FactsDatabase.h \
		ProvingEngine/URSA_Engine/URSA_ProvingEngine.h \
		ProvingEngine/NewSMT_Engine/SMT_ProvingEngine.h \
		ProvingEngine/NewSMT_Engine/Expression.h \
		ProvingEngine/SMTOut.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o import.o import.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

