#include <vector>

#include <string>

using namespace std;


vector<string> ColAxioms =
{   
     "fof(col_swap1, axiom, ! [A,B,C] : col(A,B,C) => col(B,A,C))",
     "fof(col_swap2, axiom, ! [A,B,C] : col(A,B,C) => col(B,C,A))",
     "fof(col_triv, axiom, ! [A,B] : col(A,B,B))",
//     "fof(neq_swap, axiom, ! [A,B] : neq(A,B) => neq(B,A))",
     "fof(col_trans, axiom, ! [P,Q,A,B,C] : neq(P,Q) & col(P,Q,A) & col(P,Q,B) & col(P,Q,C) => col(A,B,C))",
//     "fof(col_trans1, axiom, ! [P,Q,A,B,C] : neqcol(P,Q,A) & colcol(P,Q,B,C) => col(A,B,C))",
//     "fof(col_trans_aux1, axiom, ! [P,Q,A] : neq(P,Q) & col(P,Q,A) => neqcol(P,Q,A))",
//     "fof(col_trans_aux2, axiom, ! [P,Q,B,C] : col(P,Q,B) & col(P,Q,C) => colcol(P,Q,B,C))",
     "fof(ex1, conjecture, ! [A,B,C,D] : neq(A,B) & col(A,B,C) & col(A,B,D) => col(A,C,D))",
     "fof(ex2, conjecture, ![X , A , B , C , U , V ] : neq(A,B) & neq(C,X) & neq(B,X) & col(X,A,B) & col(X, C, X) & col(U,A,B) & col(V,C,X) => col(U, B, X))"

};

vector<string> EuclidAxioms =
{   
    "fof(proposition_test,conjecture,( ! [A,B,C] : (triangle(A,B,C) & nCol(C,A,B) => congA(A,B,C,A,C,B))))",
    "fof(proposition_test2,conjecture,( ! [A,B,C] : (isosceles(A,B,C) & nCol(C,A,B) => triangle(A,B,C))))",

    "fof(cn_eq1a, axiom, ! [A,B] : ( eq(A,B) & neq(A,B) => $false ))",
    "fof(cn_eq1b, axiom, ! [A,B] : ( eq(A,B) | neq(A,B)))",
    "fof(cn_eq1c, axiom, ! [A,B] : ( eq(A,B) => eq(B,A)))",
    "fof(cn_eq1d, axiom, ! [A,B] : ( neq(A,B) => neq(B,A)))",
    "fof(cn_cong1b, axiom, ! [A,B,C,D] : ( cong(A,B,C,D) | ncong(A,B,C,D)))",
    "fof(cn_cong1a, axiom, ! [A,B,C,D] : ( cong(A,B,C,D) & ncong(A,B,C,D) => $false ))",
    "fof(cn_col1b, axiom, ! [A,B,C] : ( col(A,B,C) | nCol(A,B,C)))",
    "fof(cn_col1a, axiom, ! [A,B,C] : ( col(A,B,C) & nCol(A,B,C) => $false ))",
    "fof(cn_lt1b, axiom, ! [A,B,C,D] : ( lt(A,B,C,D) | nlt(A,B,C,D)))",
    "fof(cn_lt1a, axiom, ! [A,B,C,D] : ( lt(A,B,C,D) & nlt(A,B,C,D) => $false ))",
    "fof(cn_bet1b, axiom, ! [A,B,C] : ( betS(A,B,C) | nbetS(A,B,C)))",
    "fof(cn_bet1a, axiom, ! [A,B,C] : ( betS(A,B,C) & nbetS(A,B,C) => $false ))",
    "fof(cn_bet_eq, axiom, ! [A,B,C,X,Y,Z] : ( eq(A,X) & eq(B,Y) & eq(C,Z) & betS(A,B,C) => betS(X,Y,Z)  ))",


    "fof(cn_equalitytransitive,axiom, ! [A,B,C] : (( eq(A,C) & eq(B,C))  => eq(A,B)))",
    "fof(cn_congruencetransitive,axiom, ! [B,C,D,E,P,Q] : (( cong(P,Q,B,C) & cong(P,Q,D,E))  => cong(B,C,D,E)))",
    "fof(cn_equalityreflexive,axiom, ! [A] : (eq(A,A)))",
    "fof(cn_congruencereflexive,axiom, ! [A,B] : ( cong(A,B,A,B)))",
    "fof(cn_equalityreverse,axiom, ! [A,B] : (cong(A,B,B,A)))",
    "fof(cn_sumofparts,axiom, ! [A,B,C,E,F,G] : (( cong(A,B,E,F) & cong(B,C,F,G) & betS(A,B,C) & betS(E,F,G))  =>  ( cong(A,C,E,G))))",
    "fof(cn_stability,axiom, ! [A,B] : ( neq(A,B) | eq(A,B)))",
    "fof(cn_equalitysub,axiom, ! [A,B,C,D] : (( eq(D,A) & col(A,B,C))  => col(D,B,C)))",
    "fof(cn_equalitysubbet,axiom, ! [A,B,C,D] : (( eq(D,A) & betS(A,B,C))  => betS(D,B,C)))",
    "fof(axiom_betweennessidentity,axiom, ! [A,B] : (nbetS(A,B,A)))",
    "fof(axiom_betweennesssymmetry,axiom, ! [A,B,C] : (( betS(A,B,C))  => betS(C,B,A)))",
    "fof(axiom_innertransitivity,axiom, ! [A,B,C,D] : (( betS(A,B,D) & betS(B,C,D))  => betS(A,B,C)))",
    "fof(axiom_connectivity,axiom, ! [A,B,C,D] : (( betS(A,B,D) & betS(A,C,D) & nbetS(A,B,C) & nbetS(A,C,B))  => eq(B,C)))",
    "fof(axiom_nocollapse,axiom, ! [A,B,C,D] : (( neq(A,B) & cong(A,B,C,D))  =>  ( neq(C,D))))",
    "fof(axiom_5_line,axiom, ! [A,B,C,D,E,F,G,H] : ((betS(A,B,C) & betS(E,F,G) &  cong(B,C,F,G) & cong(A,D,E,H) & cong(B,D,F,H) & cong(A,B,E,F))  => cong(D,C,H,G)))",
    "fof(postulate_Pasch_inner, axiom, ! [A,B,C,P,Q] : (( betS(A,P,C) & betS(B,Q,C) & nCol(A,C,B))  => ? [X] : ( ( betS(A,X,Q) & betS(B,X,P)))))",
    "fof(postulate_Pasch_outer,axiom, ! [A,B,C,P,Q] : (( betS(A,P,C) & betS(B,C,Q) & nCol(B,Q,A))  => ? [X] : ( ( betS(A,X,Q) & betS(B,P,X)))))",
    "fof(postulate_Euclid2,axiom, ! [A,B] : ( neq(A,B)   => ? [X] : ( betS(A,B,X))))",
    "fof(postulate_Euclid3,axiom, ! [A,B] : ( neq(A,B))  => ? [X] : ( ( cI(X,A,A,B))))",
    "fof(postulate_line_circle,axiom, ! [A,B,C,K,P,Q] : ( cI(K,C,P,Q) & inCirc(B,K) & neq(A,B))  => ? [X,Y] : ( ( col(A,B,X) & betS(A,B,Y) & onCirc(X,K) & onCirc(Y,K) & betS(X,B,Y))))",
    "fof(postulate_circle_circle,axiom, ! [C,D,F,G,J,K,P,Q,R,S] : ( cI(J,C,R,S) & inCirc(P,J) & outCirc(Q,J) & cI(K,D,F,G) & onCirc(P,K) & onCirc(Q,K))  => ? [X] : ( ( onCirc(X,J) & onCirc(X,K))))",
    "fof(postulate_Euclid5,axiom, ! [Ca,p,q,r,s,t] : (( betS(r,t,s) & betS(p,t,q) & betS(r,Ca,q) & cong(p,t,q,t) & cong(t,r,t,s) & nCol(p,q,s))  => ? [X] : ( ( betS(p,Ca,X) & betS(s,q,X)))))",
    "fof(axiom_circle_center_radius,axiom, ! [A,B,C,J,P] : (( cI(J,A,B,C) & onCirc(P,J))  =>  ( cong(A,P,B,C))))",
    "fof(axiom_congruentequal,axiom, ! [A,B,C,Ca,Cb,Cc] : (cong_3(A,B,C,Ca,Cb,Cc))  =>  (eT(A,B,C,Ca,Cb,Cc)))",
//"fof(axiom_ETpermutation,axiom, ! [A,B,C,Ca,Cb,Cc] : (( eT(A,B,C,Ca,Cb,Cc))  =>  ( eT(A,B,C,Cb,Cc,Ca) & eT(A,B,C,Ca,Cc,Cb) & eT(A,B,C,Cb,Ca,Cc) & eT(A,B,C,Cc,Cb,Ca) & eT(A,B,C,Cc,Ca,Cb))))",
//"fof(axiom_ETsymmetric,axiom, ! [A,B,C,Ca,Cb,Cc] : (( eT(A,B,C,Ca,Cb,Cc))  =>  ( eT(Ca,Cb,Cc,A,B,C))))",
//"fof(axiom_EFpermutation,axiom, ! [A,B,C,D,Ca,Cb,Cc,Cd] : (( eF(A,B,C,D,Ca,Cb,Cc,Cd))  =>  ( eF(A,B,C,D,Cb,Cc,Cd,Ca) & eF(A,B,C,D,Cd,Cc,Cb,Ca) & eF(A,B,C,D,Cc,Cd,Ca,Cb) & eF(A,B,C,D,Cb,Ca,Cd,Cc) & eF(A,B,C,D,Cd,Ca,Cb,Cc) & eF(A,B,C,D,Cc,Cb,Ca,Cd) & eF(A,B,C,D,Ca,Cd,Cc,Cb))))",
//"fof(axiom_halvesofequals,axiom, ! [A,B,C,D,Ca,Cb,Cc,Cd] : (( eT(A,B,C,B,C,D) & tS(A,B,C,D) & eT(Ca,Cb,Cc,Cb,Cc,Cd) & tS(Ca,Cb,Cc,Cd) & eF(A,B,D,C,Ca,Cb,Cd,Cc))  =>  ( eT(A,B,C,Ca,Cb,Cc))))",
//"fof(axiom_EFsymmetric,axiom, ! [A,B,C,D,Ca,Cb,Cc,Cd] : (( eF(A,B,C,D,Ca,Cb,Cc,Cd))  =>  ( eF(Ca,Cb,Cc,Cd,A,B,C,D))))",
//"fof(axiom_EFtransitive,axiom, ! [A,B,C,D,P,Q,R,S,Ca,Cb,Cc,Cd] : (( eF(A,B,C,D,Ca,Cb,Cc,Cd) & eF(Ca,Cb,Cc,Cd,P,Q,R,S))  =>  ( eF(A,B,C,D,P,Q,R,S))))",
//"fof(axiom_ETtransitive,axiom, ! [A,B,C,P,Q,R,Ca,Cb,Cc] : (( eT(A,B,C,Ca,Cb,Cc) & eT(Ca,Cb,Cc,P,Q,R))  =>  ( eT(A,B,C,P,Q,R))))",
//"fof(axiom_cutoff1,axiom, ! [A,B,C,D,E,Ca,Cb,Cc,Cd,Ce] : (( betS(A,B,C) & betS(Ca,Cb,Cc) & betS(E,D,C) & betS(Ce,Cd,Cc) & eT(B,C,D,Cb,Cc,Cd) & eT(A,C,E,Ca,Cc,Ce))  =>  ( eF(A,B,D,E,Ca,Cb,Cd,Ce))))",
//"fof(axiom_cutoff2,axiom, ! [A,B,C,D,E,Ca,Cb,Cc,Cd,Ce] : (( betS(B,C,D) & betS(Cb,Cc,Cd) & eT(C,D,E,Cc,Cd,Ce) & eF(A,B,D,E,Ca,Cb,Cd,Ce))  =>  ( eF(A,B,C,E,Ca,Cb,Cc,Ce))))",
//"fof(axiom_paste1,axiom, ! [A,B,C,D,E,Ca,Cb,Cc,Cd,Ce] : (( betS(A,B,C) & betS(Ca,Cb,Cc) & betS(E,D,C) & betS(Ce,Cd,Cc) & eT(B,C,D,Cb,Cc,Cd) & eF(A,B,D,E,Ca,Cb,Cd,Ce))  =>  ( eT(A,C,E,Ca,Cc,Ce))))",
//"fof(axiom_deZolt1,axiom, ! [B,C,D,E] : (( betS(B,E,D))  =>  ( neT(D,B,C,E,B,C))))",
//"fof(axiom_deZolt2,axiom, ! [A,B,C,E,F] : (( triangle(A,B,C) & betS(B,E,A) & betS(B,F,C))  =>  ( neT(A,B,C,E,B,F))))",
//"fof(axiom_paste2,axiom, ! [A,B,C,D,E,M,Ca,Cb,Cc,Cd,Ce,m] : (( betS(B,C,D) & betS(Cb,Cc,Cd) & eT(C,D,E,Cc,Cd,Ce) & eF(A,B,C,E,Ca,Cb,Cc,Ce) & betS(A,M,D) & betS(B,M,E) & betS(Ca,m,Cd) & betS(Cb,m,Ce))  =>  ( eF(A,B,D,E,Ca,Cb,Cd,Ce))))))",
//"fof(axiom_paste3,axiom, ! [A,B,C,D,M,Ca,Cb,Cc,Cd,m] : (( eT(A,B,C,Ca,Cb,Cc) & eT(A,B,D,Ca,Cb,Cd) & betS(C,M,D) & (betS(A,M,B) | eq(A,M) | eq(M,B)) & betS(Cc,m,Cd) & (betS(Ca,m,Cb) | eq(Ca,m) | eq(m,Cb)))  =>  ( eF(A,C,B,D,Ca,Cc,Cb,Cd))))",
//"fof(axiom_paste4,axiom, ! [A,B,C,D,F,G,H,J,K,L,M,P,Ce,m] : (( eF(A,B,m,D,F,K,H,G) & eF(D,B,Ce,C,G,H,M,L) & betS(A,P,C) & betS(B,P,D) & betS(K,H,M) & betS(F,G,L) & betS(B,m,D) & betS(B,Ce,C) & betS(F,J,M) & betS(K,J,L))  =>  ( eF(A,B,C,D,F,K,M,L))))",
//    "fof(defunequal,axiom,! [ A,B] : neq(A,B) =>  ( ~ eq(A,B)))",
//    "fof(defunequal2,axiom,! [ A,B] :  ( ~ eq(A,B))  => neq(A,B))",
    "fof(defcollinear,axiom,! [ A,B,C] : ( col(A,B,C) =>  ( eq(A,B) | eq(A,C) | eq(B,C) | betS(B,A,C) | betS(A,B,C) | betS(A,C,B))))",
//    "fof(defcollinear2,axiom,! [ A,B,C] :  ( (eq(A,B) | eq(A,C) | eq(B,C) | betS(B,A,C) | betS(A,B,C) | betS(A,C,B)))  => col(A,B,C))",
    "fof(defcollinear2a,axiom,! [ A,B,C] :  ( eq(A,B) => col(A,B,C)))",
    "fof(defcollinear2b,axiom,! [ A,B,C] :  ( eq(A,C) => col(A,B,C)))",
    "fof(defcollinear2c,axiom,! [ A,B,C] :  ( eq(B,C) => col(A,B,C)))",
    "fof(defcollinear2d,axiom,! [ A,B,C] :  ( betS(B,A,C) => col(A,B,C)))",
    "fof(defcollinear2e,axiom,! [ A,B,C] :  ( betS(A,B,C) => col(A,B,C)))",
    "fof(defcollinear2f,axiom,! [ A,B,C] :  ( betS(A,C,B) => col(A,B,C)))",

    "fof(defnoncollinear,axiom,! [ A,B,C] : nCol(A,B,C) =>  ( neq(A,B) & neq(A,C) & neq(B,C) & ~ betS(A,B,C) & ~ betS(A,C,B) & ~ betS(B,A,C)))",
    "fof(defnoncollinear2,axiom,! [ A,B,C] :  ( neq(A,B) & neq(A,C) & neq(B,C) & ~ betS(A,B,C) & ~ betS(A,C,B) & ~ betS(B,A,C))  => nCol(A,B,C))",
    "fof(definside,axiom,! [ P,J] : ( inCirc(P,J) => ? [ X,Y,U,V,W] :  ( (cI(J,U,V,W) & eq(P,U)) | (cI(J,U,V,W) & betS(U,Y,X) & cong(U,X,V,W) & cong(U,P,U,Y)))))",
    "fof(definside2a,axiom,! [ P,J,X,Y,U,V,W] :  ( cI(J,U,V,W) & eq(P,U))  => inCirc(P,J))",
    "fof(definside2b,axiom,! [ P,J,X,Y,U,V,W] :  ( cI(J,U,V,W) & betS(U,Y,X) & cong(U,X,V,W) & cong(U,P,U,Y)  => inCirc(P,J)))",
    "fof(defoutside,axiom,! [ P,J] : outCirc(P,J) => ? [ X,U,V,W] :  ( cI(J,U,V,W) & betS(U,X,P) & cong(U,X,V,W)))",
    "fof(defoutside2,axiom,! [ P,J, X,U,V,W] :  ( cI(J,U,V,W) & betS(U,X,P) & cong(U,X,V,W))  => outCirc(P,J))",
    "fof(defon,axiom,! [ B,J] : onCirc(B,J) => ? [ X,Y,U] :  ( cI(J,U,X,Y) & cong(U,B,X,Y)))",
    "fof(defon2,axiom,! [ B,J, X,Y,U] :  ( cI(J,U,X,Y) & cong(U,B,X,Y))  => onCirc(B,J))",
    "fof(defequilateral,axiom,! [ A,B,C] : equilateral(A,B,C) =>  ( cong(A,B,B,C) & cong(B,C,C,A)))",
    "fof(defequilateral2,axiom,! [ A,B,C] :  ( cong(A,B,B,C) & cong(B,C,C,A))  => equilateral(A,B,C))",
    "fof(deftriangle,axiom,! [ A,B,C] : triangle(A,B,C) =>  ( nCol(A,B,C)))",
    "fof(deftriangle2,axiom,! [ A,B,C] :  ( nCol(A,B,C))  => triangle(A,B,C))",
    "fof(defray,axiom,! [ A,B,C] : out(A,B,C) => ? [ X] :  ( betS(X,A,C) & betS(X,A,B)))",
    "fof(defray2,axiom,! [ A,B,C,X] :  ( betS(X,A,C) & betS(X,A,B))  => out(A,B,C))",
    "fof(deflessthan,axiom,! [ A,B,C,D] : lt(A,B,C,D) => ? [ X] :  ( betS(C,X,D) & cong(C,X,A,B)))",
    "fof(deflessthan2,axiom,! [ A,B,C,D, X] :  ( betS(C,X,D) & cong(C,X,A,B))  => lt(A,B,C,D))",
    "fof(defmidpoint,axiom,! [ A,B,C] : midpoint(A,B,C) =>  ( betS(A,B,C) & cong(A,B,B,C)))",
    "fof(defmidpoint2,axiom,! [ A,B,C] :  ( betS(A,B,C) & cong(A,B,B,C))  => midpoint(A,B,C))",
    "fof(defequalangles,axiom,! [ A,B,C,Ca,Cb,Cc] : congA(A,B,C,Ca,Cb,Cc) => ? [ U,V,u,v] :  ( out(B,A,U) & out(B,C,V) & out(Cb,Ca,u) & out(Cb,Cc,v) & cong(B,U,Cb,u) & cong(B,V,Cb,v) & cong(U,V,u,v) & nCol(A,B,C)))",
    "fof(defequalangles2,axiom,! [ A,B,C,Ca,Cb,Cc, U,V,u,v] :  ( out(B,A,U) & out(B,C,V) & out(Cb,Ca,u) & out(Cb,Cc,v) & cong(B,U,Cb,u) & cong(B,V,Cb,v) & cong(U,V,u,v) & nCol(A,B,C))  => congA(A,B,C,Ca,Cb,Cc))",
    "fof(defsupplement,axiom,! [ A,B,C,D,F] : supp(A,B,C,D,F) =>  ( out(B,C,D) & betS(A,B,F)))",
    "fof(defsupplement2,axiom,! [ A,B,C,D,F] :  ( out(B,C,D) & betS(A,B,F))  => supp(A,B,C,D,F))",
    "fof(defrightangle,axiom,! [ A,B,C] : per(A,B,C) => ? [ X] :  ( betS(A,B,X) & cong(A,B,X,B) & cong(A,C,X,C) & neq(B,C)))",
    "fof(defrightangle2,axiom,! [ A,B,C, X] :  ( betS(A,B,X) & cong(A,B,X,B) & cong(A,C,X,C) & neq(B,C))  => per(A,B,C))",
    "fof(defperpat,axiom,! [ P,Q,A,B,C] : perp_at(P,Q,A,B,C) => ? [ X] :  ( col(P,Q,C) & col(A,B,C) & col(A,B,X) & per(X,C,P)))",
    "fof(defperpat2,axiom,! [ P,Q,A,B,C, X] :  ( col(P,Q,C) & col(A,B,C) & col(A,B,X) & per(X,C,P))  => perp_at(P,Q,A,B,C))",
    "fof(defperpendicular,axiom,! [ P,Q,A,B] : perp(P,Q,A,B) => ? [ X] :  ( perp_at(P,Q,A,B,X)))",
    "fof(defperpendicular2,axiom,! [ P,Q,A,B, X] :  ( perp_at(P,Q,A,B,X))  => perp(P,Q,A,B))",
    "fof(definterior,axiom,! [ A,B,C,P] : inAngle(A,B,C,P) => ? [ X,Y] :  ( out(B,A,X) & out(B,C,Y) & betS(X,P,Y)))",
    "fof(definterior2,axiom,! [ A,B,C,P, X,Y] :  ( out(B,A,X) & out(B,C,Y) & betS(X,P,Y))  => inAngle(A,B,C,P))",
    "fof(defoppositeside,axiom,! [ P,A,B,Q] : tS(P,A,B,Q) => ? [ X] :  ( betS(P,X,Q) & col(A,B,X) & nCol(A,B,P)))",
    "fof(defoppositeside2,axiom,! [ P,A,B,Q, X] :  ( betS(P,X,Q) & col(A,B,X) & nCol(A,B,P))  => tS(P,A,B,Q))",
    "fof(defsameside,axiom,! [ P,Q,A,B] : oS(P,Q,A,B) => ? [ X,U,V] :  ( col(A,B,U) & col(A,B,V) & betS(P,U,X) & betS(Q,V,X) & nCol(A,B,P) & nCol(A,B,Q)))",
    "fof(defsameside2,axiom,! [ P,Q,A,B, X,U,V] :  ( col(A,B,U) & col(A,B,V) & betS(P,U,X) & betS(Q,V,X) & nCol(A,B,P) & nCol(A,B,Q))  => oS(P,Q,A,B))",
    "fof(defisosceles,axiom,! [ A,B,C] : isosceles(A,B,C) =>  ( triangle(A,B,C) & cong(A,B,A,C)))",
    "fof(defisosceles2,axiom,! [ A,B,C] :  ( triangle(A,B,C) & cong(A,B,A,C))  => isosceles(A,B,C))",
    "fof(defcut,axiom,! [ A,B,C,D,E] : cut(A,B,C,D,E) =>  ( betS(A,E,B) & betS(C,E,D) & nCol(A,B,C) & nCol(A,B,D)))",
    "fof(defcut2,axiom,! [ A,B,C,D,E] :  ( betS(A,E,B) & betS(C,E,D) & nCol(A,B,C) & nCol(A,B,D))  => cut(A,B,C,D,E))",
    "fof(deftrianglecongruence,axiom,! [ A,B,C,Ca,Cb,Cc] : cong_3(A,B,C,Ca,Cb,Cc) =>  ( cong(A,B,Ca,Cb) & cong(B,C,Cb,Cc) & cong(A,C,Ca,Cc) & triangle(A,B,C)))",
    "fof(deftrianglecongruence2,axiom,! [ A,B,C,Ca,Cb,Cc] :  ( cong(A,B,Ca,Cb) & cong(B,C,Cb,Cc) & cong(A,C,Ca,Cc) & triangle(A,B,C))  => cong_3(A,B,C,Ca,Cb,Cc))",
    "fof(defanglelessthan,axiom,! [ A,B,C,D,E,F] : ltA(A,B,C,D,E,F) => ? [ U,X,V] :  ( betS(U,X,V) & out(E,D,U) & out(E,F,V) & congA(A,B,C,D,E,X)))",
    "fof(defanglelessthan2,axiom,! [ A,B,C,D,E,F, U,X,V] :  ( betS(U,X,V) & out(E,D,U) & out(E,F,V) & congA(A,B,C,D,E,X))  => ltA(A,B,C,D,E,F))",
    "fof(deftogethergreater,axiom,! [ A,B,C,D,E,F] : tG(A,B,C,D,E,F) => ? [ X] :  ( betS(A,B,X) & cong(B,X,C,D) & lt(E,F,A,X)))",
    "fof(deftogethergreater2,axiom,! [ A,B,C,D,E,F, X] :  ( betS(A,B,X) & cong(B,X,C,D) & lt(E,F,A,X))  => tG(A,B,C,D,E,F))",
    "fof(deftogetherfour,axiom,! [ A,B,C,D,E,F,G,H] : tT(A,B,C,D,E,F,G,H) => ? [ X] :  ( betS(E,F,X) & cong(F,X,G,H) & tG(A,B,C,D,E,X)))",
    "fof(deftogetherfour2,axiom,! [ A,B,C,D,E,F,G,H, X] :  ( betS(E,F,X) & cong(F,X,G,H) & tG(A,B,C,D,E,X))  => tT(A,B,C,D,E,F,G,H))",
    "fof(deftworightangles,axiom,! [ A,B,C,D,E,F] : rT(A,B,C,D,E,F) => ? [ X,Y,Z,U,V] :  ( supp(X,Y,U,V,Z) & congA(A,B,C,X,Y,U) & congA(D,E,F,V,Y,Z)))",
    "fof(deftworightangles2,axiom,! [ A,B,C,D,E,F, X,Y,Z,U,V] :  ( supp(X,Y,U,V,Z) & congA(A,B,C,X,Y,U) & congA(D,E,F,V,Y,Z))  => rT(A,B,C,D,E,F))",
    "fof(defmeet,axiom,! [ A,B,C,D] : meet(A,B,C,D) => ? [ X] :  ( neq(A,B) & neq(C,D) & col(A,B,X) & col(C,D,X)))",
    "fof(defmeet2,axiom,! [ A,B,C,D, X] :  ( neq(A,B) & neq(C,D) & col(A,B,X) & col(C,D,X))  => meet(A,B,C,D))",
    "fof(defcross,axiom,! [ A,B,C,D] : cR(A,B,C,D) => ? [ X] :  ( betS(A,X,B) & betS(C,X,D)))",
    "fof(defcross2,axiom,! [ A,B,C,D, X] :  ( betS(A,X,B) & betS(C,X,D))  => cR(A,B,C,D))",
    "fof(deftarski_parallel,axiom,! [ A,B,C,D] : tP(A,B,C,D) =>  ( neq(A,B) & neq(C,D) & ~meet(A,B,C,D) & oS(C,D,A,B)))",
    "fof(deftarski_parallel2,axiom,! [ A,B,C,D] :  ( neq(A,B) & neq(C,D) & ~meet(A,B,C,D) & oS(C,D,A,B))  => tP(A,B,C,D))",
    "fof(defparallel,axiom,! [ A,B,C,D] : par(A,B,C,D) => ? [ U,V,u,v,X] :  ( neq(A,B) & neq(C,D) & col(A,B,U) & col(A,B,V) & neq(U,V) & col(C,D,u) & col(C,D,v) & neq(u,v) & ~ meet(A,B,C,D) & betS(U,X,v) & betS(u,X,V)))",
    "fof(defparallel2,axiom,! [ A,B,C,D, U,V,u,v,X] :  ( neq(A,B) & neq(C,D) & col(A,B,U) & col(A,B,V) & neq(U,V) & col(C,D,u) & col(C,D,v) & neq(u,v) & ~ meet(A,B,C,D) & betS(U,X,v) & betS(u,X,V))  => par(A,B,C,D))",
    "fof(defanglesum,axiom,! [ A,B,C,D,E,F,P,Q,R] : sumA(A,B,C,D,E,F,P,Q,R) => ? [ X] :  ( congA(A,B,C,P,Q,X) & congA(D,E,F,X,Q,R) & betS(P,X,R)))",
    "fof(defanglesum2,axiom,! [ A,B,C,D,E,F,P,Q,R, X] :  ( congA(A,B,C,P,Q,X) & congA(D,E,F,X,Q,R) & betS(P,X,R))  => sumA(A,B,C,D,E,F,P,Q,R))",
    "fof(defparallelogram,axiom,! [ A,B,C,D] : pG(A,B,C,D) =>  ( par(A,B,C,D) & par(A,D,B,C)))",
    "fof(defparallelogram2,axiom,! [ A,B,C,D] :  ( par(A,B,C,D) & par(A,D,B,C))  => pG(A,B,C,D))",
    "fof(defsquare,axiom,! [ A,B,C,D] : sQ(A,B,C,D) =>  ( cong(A,B,C,D) & cong(A,B,B,C) & cong(A,B,D,A) & per(D,A,B) & per(A,B,C) & per(B,C,D) & per(C,D,A)))",
    "fof(defsquare2,axiom,! [ A,B,C,D] :  ( cong(A,B,C,D) & cong(A,B,B,C) & cong(A,B,D,A) & per(D,A,B) & per(A,B,C) & per(B,C,D) & per(C,D,A))  => sQ(A,B,C,D))",
    "fof(defrectangle,axiom,! [ A,B,C,D] : rE(A,B,C,D) =>  ( per(D,A,B) & per(A,B,C) & per(B,C,D) & per(C,D,A) & cR(A,C,B,D)))",
    "fof(defrectangle2,axiom,! [ A,B,C,D] :  ( per(D,A,B) & per(A,B,C) & per(B,C,D) & per(C,D,A) & cR(A,C,B,D))  => rE(A,B,C,D))",
  //  "fof(defsegmentcutscircle,axiom,! [ A,B,J,E] : (A,B,J,E) =>  ( cI(J,C,P,Q) & onCirc(E,J) & betS(A,E,B) & inCirc(A,J) & outCirc(B,J)))",
  //  "fof(defsegmentcutscircle2,axiom,! [ A,B,J,E] :  ( cI(J,C,P,Q) & onCirc(E,J) & betS(A,E,B) & inCirc(A,J) & outCirc(B,J))  => (A,B,J,E))",
  //  "fof(deflinecutscircle,axiom,! [ A,B,J] : (A,B,J) => ? [ C,P,Q,X,Y,Z] :  ( cI(C,J,C,P,Q) & col(A,B,X) & col(A,B,Y) & col(A,B,Z) & (X,Y,J,Z)))",
  //  "fof(deflinecutscircle2,axiom,! [ A,B,J] : ! [ C,P,Q,X,Y,Z] :  ( cI(C,J,C,P,Q) & col(A,B,X) & col(A,B,Y) & col(A,B,Z) & (X,Y,J,Z))  => (A,B,J))",
  //  "fof(deftangentline,axiom,! [ A,B,J,E] : (A,B,J,E) => ? [ C,P,Q] :  ( cI(J,C,P,Q) & onCirc(E,J) & betS(A,E,B) & ~(A,B,J)))",
  //  "fof(deftangentline2,axiom,! [ A,B,J,E] : ! [ C,P,Q] :  ( cI(J,C,P,Q) & onCirc(E,J) & betS(A,E,B) & ~(A,B,J))  => (A,B,J,E))",
    "fof(defcongruentrectangles,axiom,! [ A,B,C,D,Ca,Cb,Cc,Cd] : rC(A,B,C,D,Ca,Cb,Cc,Cd) =>  ( rE(A,B,C,D) & rE(Ca,Cb,Cc,Cd) & cong(A,B,Ca,Cb) & cong(B,C,Cb,Cc)))",
    "fof(defcongruentrectangles2,axiom,! [ A,B,C,D,Ca,Cb,Cc,Cd] :  ( rE(A,B,C,D) & rE(Ca,Cb,Cc,Cd) & cong(A,B,Ca,Cb) & cong(B,C,Cb,Cc))  => rC(A,B,C,D,Ca,Cb,Cc,Cd))",
    "fof(defequalrectangles,axiom,! [ A,B,C,D,Ca,Cb,Cc,Cd] : eR(A,B,C,D,Ca,Cb,Cc,Cd) => ? [ X,Y,Z,U,x,z,u,w,W] :  ( rC(A,B,C,D,X,Y,Z,U) & rC(Ca,Cb,Cc,Cd,x,Y,z,u) & betS(x,Y,Z) & betS(X,Y,z) & betS(W,U,w)))",
    "fof(defequalrectangles2,axiom,! [ A,B,C,D,Ca,Cb,Cc,Cd, X,Y,Z,U,x,z,u,w,W] :  ( rC(A,B,C,D,X,Y,Z,U) & rC(Ca,Cb,Cc,Cd,x,Y,z,u) & betS(x,Y,Z) & betS(X,Y,z) & betS(W,U,w))  => eR(A,B,C,D,Ca,Cb,Cc,Cd))",
    "fof(defbaserectangle,axiom,! [ A,B,C,D,E] : bR(A,B,C,D,E) =>  ( rE(B,C,D,E) & col(D,E,A)))",
    "fof(defbaserectangle2,axiom,! [ A,B,C,D,E] :  ( rE(B,C,D,E) & col(D,E,A))  => bR(A,B,C,D,E))",
    "fof(deffigurerectangle,axiom,! [ A,B,C,D,E,F,G,H] : fR(A,B,C,D,E,F,G,H) =>  ( rE(E,F,G,H) & betS(E,B,F) & betS(H,D,G) & bR(C,B,D,G,F) & bR(A,B,D,H,E)))",
    "fof(deffigurerectangle2,axiom,! [ A,B,C,D,E,F,G,H] :  ( rE(E,F,G,H) & betS(E,B,F) & betS(H,D,G) & bR(C,B,D,G,F) & bR(A,B,D,H,E))  => fR(A,B,C,D,E,F,G,H))",
    "fof(defequaltriangles,axiom,! [ A,B,C,Ca,Cb,Cc] : tE(A,B,C,Ca,Cb,Cc) => ? [ X,Y,x,y] :  ( rE(A,B,X,Y) & rE(Ca,Cb,x,y) & col(X,Y,C) & col(x,y,Cc) & eR(A,B,X,Y,Ca,Cb,x,y)))",
    "fof(defequaltriangles2,axiom,! [ A,B,C,Ca,Cb,Cc, X,Y,x,y] :  ( rE(A,B,X,Y) & rE(Ca,Cb,x,y) & col(X,Y,C) & col(x,y,Cc) & eR(A,B,X,Y,Ca,Cb,x,y))  => tE(A,B,C,Ca,Cb,Cc))",
    "fof(defequalfigures,axiom,! [ A,B,C,D,Ca,Cb,Cc,Cd] : fE(A,B,C,D,Ca,Cb,Cc,Cd) => ? [ X,Y,Z,U,x,y,z,u] :  ( tS(A,B,C,D) & tS(Ca,Cb,Cc,Cd) & fR(A,B,C,D,X,Y,Z,U) & fR(Ca,Cb,Cc,Cd,x,y,z,u) & eR(X,Y,Z,U,x,y,z,u)))",
    "fof(defequalfigures2,axiom,! [ A,B,C,D,Ca,Cb,Cc,Cd, X,Y,Z,U,x,y,z,u] :  ( tS(A,B,C,D) & tS(Ca,Cb,Cc,Cd) & fR(A,B,C,D,X,Y,Z,U) & fR(Ca,Cb,Cc,Cd,x,y,z,u) & eR(X,Y,Z,U,x,y,z,u))  => fE(A,B,C,D,Ca,Cb,Cc,Cd))",
    "fof(defequaltrianglefigure,axiom,! [ A,B,C,Ca,Cb,Cc,Cd] : tF(A,B,C,Ca,Cb,Cc,Cd) => ? [ X,Y,x,y,z,u] :  ( bR(A,B,C,X,Y) & fR(Ca,Cb,Cc,Cd,x,y,z,u) & eR(B,C,X,Y,x,y,z,u)))",
    "fof(defequaltrianglefigure2,axiom,! [ A,B,C,Ca,Cb,Cc,Cd, X,Y,x,y,z,u] :  ( bR(A,B,C,X,Y) & fR(Ca,Cb,Cc,Cd,x,y,z,u) & eR(B,C,X,Y,x,y,z,u))  => tF(A,B,C,Ca,Cb,Cc,Cd))",
//    "fof(defcirclecut,axiom,! [ J,K,B] : (J,K,B) => ? [ X,Y] :  ( onCirc(J,B) & onCirc(K,B) & onCirc(K,X) & onCirc(K,Y) & inCirc(J,X) & outCirc(J,Y)))",
//    "fof(defcirclecut2,axiom,! [ J,K,B, X,Y] :  ( onCirc(J,B) & onCirc(K,B) & onCirc(K,X) & onCirc(K,Y) & inCirc(J,X) & outCirc(J,Y))  => (J,K,B))"


    "fof(lemma_equalitysymmetric,conjecture,(  ! [A,B] : ((eq(B,A)) => (eq(A,B)))))",
    "fof(lemma_inequalitysymmetric,conjecture,(  ! [A,B] : ((neq(A,B)) => (neq(B,A)))))",
    "fof(lemma_congruencesymmetric,conjecture,(  ! [A,B,C,D] : ((cong(B,C,A,D)) => (cong(A,D,B,C)))))",
    "fof(lemma_congruencetransitive,conjecture,(  ! [A,B,C,D,E,F] : ((cong(A,B,C,D) & cong(C,D,E,F)) => (cong(A,B,E,F)))))",
    "fof(lemma_3_6a,conjecture,(  ! [A,B,C,D] : ((betS(A,B,C) & betS(A,C,D)) => (betS(B,C,D)))))",
    "fof(lemma_betweennotequal,conjecture,(  ! [A,B,C] : ((betS(A,B,C)) => (neq(B,C) & neq(A,B) & neq(A,C)))))",
    //"fof(lemma_betweennotequal,conjecture,(  ! [A,B,C] : ((betS(A,B,C)) => (neq(B,C)))))",

    "fof(lemma_extensionunique,conjecture,(  ! [A,B,E,F] : ((betS(A,B,E) & betS(A,B,F) & cong(B,E,B,F)) => (eq(E,F))))",

    //    "fof(lemma_extensionunique,conjecture,(  ! [A,B,E,F] : ((betS(A,B,E) & betS(A,B,F) & cong(B,E,B,F) & neq(E,F)) => $false ))",

        "fof(lemma_doublereverse,conjecture,(  ! [A,B,C,D] : ((cong(A,B,C,D)) => (cong(D,C,B,A) & cong(B,A,D,C)))))",
    "fof(lemma_congruenceflip,conjecture,(  ! [A,B,C,D] : ((cong(A,B,C,D)) => (cong(B,A,D,C) & cong(B,A,C,D) & cong(A,B,D,C)))))",
    "fof(lemma_congruenceflip1,conjecture,(  ! [A,B,C,D] : ((cong(A,B,C,D)) => (cong(B,A,D,C)))))",
    "fof(lemma_congruenceflip2,conjecture,(  ! [A,B,C,D] : ((cong(A,B,C,D)) => (cong(B,A,C,D)))))",
    "fof(lemma_congruenceflip3,conjecture,(  ! [A,B,C,D] : ((cong(A,B,C,D)) => (cong(A,B,D,C)))))",



    "fof(lemma_localextension,conjecture,(  ! [A,B,Q] : ((neq(A,B) & neq(B,Q)) => ? [X] : (betS(A,B,X) & cong(B,X,B,Q)))))",
    "fof(lemma_betweennesspreserved,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((cong(A,B,Xa,Xb) & cong(A,C,Xa,Xc) & cong(B,C,Xb,Xc) & betS(A,B,C)) => (betS(Xa,Xb,Xc)))))",
    "fof(lemma_differenceofparts,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((cong(A,B,Xa,Xb) & cong(A,C,Xa,Xc) & betS(A,B,C) & betS(Xa,Xb,Xc)) => (cong(B,C,Xb,Xc)))))",
    "fof(lemma_3_7a,conjecture,(  ! [A,B,C,D] : ((betS(A,B,C) & betS(B,C,D)) => (betS(A,C,D)))))",
    "fof(lemma_3_5b,conjecture,(  ! [A,B,C,D] : ((betS(A,B,D) & betS(B,C,D)) => (betS(A,C,D)))))",
    "fof(lemma_3_6b,conjecture,(  ! [A,B,C,D] : ((betS(A,B,C) & betS(A,C,D)) => (betS(A,B,D)))))",
    "fof(lemma_3_7b,conjecture,(  ! [A,B,C,D] : ((betS(A,B,C) & betS(B,C,D)) => (betS(A,B,D)))))",
    "fof(lemma_partnotequalwhole,conjecture,(  ! [A,B,C] : ((betS(A,B,C)) => (ncong(A,B,A,C)))))",
    "fof(lemma_NCdistinct,conjecture,(  ! [A,B,C] : ((nCol(A,B,C)) => (neq(A,B) & neq(B,C) & neq(A,C) & neq(B,A) & neq(C,B) & neq(C,A)))))",
    "fof(proposition_01,conjecture,(  ! [A,B] : ((neq(A,B)) => ? [X] : (equilateral(A,B,X) & triangle(A,B,X)))))",
    "fof(proposition_02,conjecture,(  ! [A,B,C] : ((neq(A,B) & neq(B,C)) => ? [X] : (cong(A,X,B,C)))))",
    "fof(lemma_extension,conjecture,(  ! [A,B,P,Q] : ((neq(A,B) & neq(P,Q)) => ? [X] : (betS(A,B,X) & cong(B,X,P,Q)))))",
    "fof(lemma_lessthancongruence2,conjecture,(  ! [A,B,C,D,E,F] : ((lt(A,B,C,D) & cong(A,B,E,F)) => (lt(E,F,C,D)))))",
    "fof(lemma_lessthancongruence,conjecture,(  ! [A,B,C,D,E,F] : ((lt(A,B,C,D) & cong(C,D,E,F)) => (lt(A,B,E,F)))))",
    "fof(lemma_outerconnectivity,conjecture,(  ! [A,B,C,D] : ((betS(A,B,C) & betS(A,B,D) & nbetS(B,C,D) & nbetS(B,D,C)) => (eq(C,D)))))",
    "fof(lemma_trichotomy1,conjecture,(  ! [A,B,C,D] : ((nlt(A,B,C,D) & nlt(C,D,A,B) & neq(A,B) & neq(C,D)) => (cong(A,B,C,D)))))",
    "fof(lemma_interior5,conjecture,(  ! [A,B,C,D,Xa,Xb,Xc,Xd] : ((betS(A,B,C) & betS(Xa,Xb,Xc) & cong(A,B,Xa,Xb) & cong(B,C,Xb,Xc) & cong(A,D,Xa,Xd) & cong(C,D,Xc,Xd)) => (cong(B,D,Xb,Xd)))))",
    "fof(lemma_collinear1,conjecture,(  ! [A,B,C] : ((col(A,B,C)) => (col(B,A,C)))))",
    "fof(lemma_collinear2,conjecture,(  ! [A,B,C] : ((col(A,B,C)) => (col(B,C,A)))))",
    "fof(lemma_collinearorder,conjecture,(  ! [A,B,C] : ((col(A,B,C)) => (col(B,A,C) & col(B,C,A) & col(C,A,B) & col(A,C,B) & col(C,B,A)))))",
    "fof(lemma_NCorder,conjecture,(  ! [A,B,C] : ((nCol(A,B,C)) => (nCol(B,A,C) & nCol(B,C,A) & nCol(C,A,B) & nCol(A,C,B) & nCol(C,B,A)))))",
    "fof(lemma_collinear4,conjecture,(  ! [A,B,C,D] : ((col(A,B,C) & col(A,B,D) & neq(A,B)) => (col(B,C,D)))))",
    "fof(lemma_collinear5,conjecture,(  ! [A,B,C,D,E] : ((neq(A,B) & col(A,B,C) & col(A,B,D) & col(A,B,E)) => (col(C,D,E)))))",
    "fof(lemma_NChelper,conjecture,(  ! [A,B,C,P,Q] : ((nCol(A,B,C) & col(A,B,P) & col(A,B,Q) & neq(P,Q)) => (nCol(P,Q,C)))))",
    "fof(lemma_fiveline,conjecture,(  ! [A,B,C,D,Xa,Xb,Xc,Xd] : ((col(A,B,C) & cong(A,B,Xa,Xb) & cong(B,C,Xb,Xc) & cong(A,D,Xa,Xd) & cong(C,D,Xc,Xd) & cong(A,C,Xa,Xc) & neq(A,C)) => (cong(B,D,Xb,Xd)))))",
    "fof(lemma_twolines,conjecture,(  ! [A,B,C,D,E,F] : ((cut(A,B,C,D,E) & cut(A,B,C,D,F) & nCol(B,C,D)) => (eq(E,F)))))",
    "fof(lemma_ray2,conjecture,(  ! [A,B,C] : ((out(A,B,C)) => (neq(A,B)))))",
    "fof(lemma_ray,conjecture,(  ! [A,B,P] : ((out(A,B,P) & neq(P,B) & nbetS(A,P,B)) => (betS(A,B,P)))))",
    "fof(lemma_ray1,conjecture,(  ! [A,B,P] : ((out(A,B,P)) => ((betS(A,P,B) | eq(B,P) | betS(A,B,P))))))",
    "fof(lemma_ray3,conjecture,(  ! [B,C,D,V] : ((out(B,C,D) & out(B,C,V)) => (out(B,D,V)))))",
    "fof(lemma_raystrict,conjecture,(  ! [A,B,C] : ((out(A,B,C)) => (neq(A,C)))))",
    //"fof(lemma_ray4,conjecture,(  ! [A,B,E] : (((betS(A,E,B) | eq(E,B) | betS(A,B,E)) & neq(A,B)) => (out(A,B,E)))))",
    "fof(lemma_ray4_1,conjecture,(  ! [A,B,E] : ((betS(A,E,B) & neq(A,B)) => (out(A,B,E)))))",
    "fof(lemma_ray4_2,conjecture,(  ! [A,B,E] : ((eq(E,B) & neq(A,B)) => (out(A,B,E)))))",
    "fof(lemma_ray4_3,conjecture,(  ! [A,B,E] : ((betS(A,B,E) & neq(A,B)) => (out(A,B,E)))))",


    "fof(lemma_ray5,conjecture,(  ! [A,B,C] : ((out(A,B,C)) => (out(A,C,B)))))",
    "fof(lemma_rayimpliescollinear,conjecture,(  ! [A,B,C] : ((out(A,B,C)) => (col(A,B,C)))))",
    "fof(lemma_tworays,conjecture,(  ! [A,B,C] : ((out(A,B,C) & out(B,A,C)) => (betS(A,C,B)))))",
    //"fof(lemma_twolines2,conjecture,(  ! [A,B,C,D,P,Q] : ((neq(A,B) & neq(C,D) & col(P,A,B) & col(P,C,D) & col(Q,A,B) & col(Q,C,D) & n(col(A,C,D) & col(B,C,D))) => (eq(P,Q)))))",
    // trying another encoding:
    "fof(lemma_twolines2,conjecture,(  ! [A,B,C,D,P,Q] : ((neq(A,B) & neq(C,D) & col(P,A,B) & col(P,C,D) & col(Q,A,B) & col(Q,C,D)) => ((col(A,C,D) & col(B,C,D)) || eq(P,Q)))))",
    
    "fof(lemma_supplements,conjecture,(  ! [A,B,C,D,F,Xadeflessthan,Xb,Xc,Xd,Xf] : ((congA(A,B,C,Xa,Xb,Xc) & supp(A,B,C,D,F) & supp(Xa,Xb,Xc,Xd,Xf)) => (congA(D,B,F,Xd,Xb,Xf)))))",
    "fof(lemma_supplementsymmetric,conjecture,(  ! [A,B,C,D,E] : ((supp(A,B,C,E,D)) => (supp(D,B,E,C,A)))))",
    "fof(lemma_collinearitypreserved,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((col(A,B,C) & cong(A,B,Xa,Xb) & cong(A,C,Xa,Xc) & cong(B,C,Xb,Xc)) => (col(Xa,Xb,Xc)))))",
    "fof(lemma_trichotomy2,conjecture,(  ! [A,B,C,D] : ((lt(A,B,C,D)) => (nlt(C,D,A,B)))))",
    "fof(lemma_lessthannotequal,conjecture,(  ! [A,B,C,D] : ((lt(A,B,C,D)) => (neq(A,B) & neq(C,D)))))",
    "fof(lemma_layoff,conjecture,(  ! [A,B,C,D] : ((neq(A,B) & neq(C,D)) => ? [X] : (out(A,B,X) & cong(A,X,C,D)))))",
    "fof(lemma_layoffunique,conjecture,(  ! [A,B,C,D] : ((out(A,B,C) & out(A,B,D) & cong(A,C,A,D)) => (eq(C,D)))))",
    "fof(lemma_lessthanbetween,conjecture,(  ! [A,B,C] : ((lt(A,B,A,C) & out(A,B,C)) => (betS(A,B,C)))))",
    "fof(lemma_lessthantransitive,conjecture,(  ! [A,B,C,D,E,F] : ((lt(A,B,C,D) & lt(C,D,E,F)) => (lt(A,B,E,F)))))",
    "fof(lemma_lessthanadditive,conjecture,(  ! [A,B,C,D,E,F] : ((lt(A,B,C,D) & betS(A,B,E) & betS(C,D,F) & cong(B,E,D,F)) => (lt(A,E,C,F)))))",
    "fof(lemma_subtractequals,conjecture,(  ! [A,B,C,D,E] : ((betS(A,B,C) & betS(A,D,E) & cong(B,C,D,E) & betS(A,C,E)) => (betS(A,B,D)))))",
    "fof(lemma_crossbar,conjecture,(  ! [A,B,C,E,U,V] : ((triangle(A,B,C) & betS(A,E,C) & out(B,A,U) & out(B,C,V)) => ? [X] : (out(B,E,X) & betS(U,X,V)))))",
    "fof(lemma_ABCequalsCBA,conjecture,(  ! [A,B,C] : ((nCol(A,B,C)) => (congA(A,B,C,C,B,A)))))",
    "fof(lemma_equalanglessymmetric,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((congA(A,B,C,Xa,Xb,Xc)) => (congA(Xa,Xb,Xc,A,B,C)))))",
    "fof(lemma_angledistinct,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((congA(A,B,C,Xa,Xb,Xc)) => (neq(A,B) & neq(B,C) & neq(A,C) & neq(Xa,Xb) & neq(Xb,Xc) & neq(Xa,Xc)))))",
    "fof(lemma_4_19,conjecture,(  ! [A,B,C,D] : ((betS(A,D,B) & cong(A,C,A,D) & cong(B,D,B,C)) => (eq(C,D)))))",
    "fof(lemma_collinearbetween,conjecture,(  ! [A,B,C,D,E,F,H] : ((col(A,E,B) & col(C,F,D) & neq(A,B) & neq(C,D) & neq(A,E) & neq(F,D) & nmeet(A,B,C,D) & betS(A,H,D) & col(E,F,H)) => (betS(E,H,F)))))",
    "fof(lemma_9_5a,conjecture,(  ! [A,B,C,P,Q,R] : ((tS(P,A,B,C) & betS(R,P,Q) & nCol(R,Q,C) & col(A,B,R)) => (tS(Q,A,B,C)))))",
    "fof(lemma_9_5b,conjecture,(  ! [A,B,C,P,Q,R] : ((tS(P,A,B,C) & betS(R,Q,P) & nCol(C,P,R) & col(A,B,R)) => (tS(Q,A,B,C)))))",
    "fof(lemma_9_5,conjecture,(  ! [A,B,C,P,Q,R] : ((tS(P,A,B,C) & out(R,Q,P) & col(A,B,R)) => (tS(Q,A,B,C)))))",
    "fof(lemma_samesidereflexive,conjecture,(  ! [A,B,P] : ((nCol(A,B,P)) => (oS(P,P,A,B)))))",
    "fof(lemma_samesidesymmetric,conjecture,(  ! [A,B,P,Q] : ((oS(P,Q,A,B)) => (oS(Q,P,A,B) & oS(P,Q,B,A) & oS(Q,P,B,A)))))",
    "fof(lemma_oppositesidesymmetric,conjecture,(  ! [A,B,P,Q] : ((tS(P,A,B,Q)) => (tS(Q,A,B,P)))))",
    "fof(lemma_oppositesideflip,conjecture,(  ! [A,B,P,Q] : ((tS(P,A,B,Q)) => (tS(P,B,A,Q)))))",
    "fof(lemma_samesidecollinear,conjecture,(  ! [A,B,C,P,Q] : ((oS(P,Q,A,B) & col(A,B,C) & neq(A,C)) => (oS(P,Q,A,C)))))",
    "fof(lemma_equalanglesNC,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((congA(A,B,C,Xa,Xb,Xc)) => (nCol(Xa,Xb,Xc)))))",
    "fof(lemma_ondiameter,conjecture,(  ! [D,F,K,M,N,P,Q] : ((cI(K,F,P,Q) & cong(F,D,P,Q) & cong(F,M,P,Q) & betS(D,F,M) & betS(D,N,M)) => (inCirc(N,K)))))",
    "fof(proposition_03,conjecture,(  ! [A,B,C,D,E,F] : ((lt(C,D,A,B) & cong(E,F,A,B)) => ? [X] : (betS(E,X,F) & cong(E,X,C,D)))))",
    "fof(proposition_04,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((cong(A,B,Xa,Xb) & cong(A,C,Xa,Xc) & congA(B,A,C,Xb,Xa,Xc)) => (cong(B,C,Xb,Xc) & congA(A,B,C,Xa,Xb,Xc) & congA(A,C,B,Xa,Xc,Xb)))))",

    "fof(proposition_04modified1a,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((congcong(A,B,Xa,Xb,A,C,Xa,Xc) & congA(B,A,C,Xb,Xa,Xc)) => (cong(B,C,Xb,Xc)))))",
    "fof(proposition_04modified1b,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((congcong(A,B,Xa,Xb,A,C,Xa,Xc) & congA(B,A,C,Xb,Xa,Xc)) => (congA(A,B,C,Xa,Xb,Xc)))))",
    "fof(proposition_04modified1c,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((congcong(A,B,Xa,Xb,A,C,Xa,Xc) & congA(B,A,C,Xb,Xa,Xc)) => (congA(A,C,B,Xa,Xc,Xb)))))",

    "fof(proposition_04modified2,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((cong(A,B,Xa,Xb) & cong(A,C,Xa,Xc) => congcong(A,B,Xa,Xb,A,C,Xa,Xc)))))",
 
    "fof(lemma_equalangleshelper,conjecture,(  ! [A,B,C,Xa,Xb,Xc,Xp,Xq] : ((congA(A,B,C,Xa,Xb,Xc) & out(Xb,Xa,Xp) & out(Xb,Xc,Xq)) => (congA(A,B,C,Xp,Xb,Xq)))))",
    "fof(lemma_equalanglestransitive,conjecture,(  ! [A,B,C,D,E,F,P,Q,R] : ((congA(A,B,C,D,E,F) & congA(D,E,F,P,Q,R)) => (congA(A,B,C,P,Q,R)))))",
    "fof(lemma_equalanglesreflexive,conjecture,(  ! [A,B,C] : ((nCol(A,B,C)) => (congA(A,B,C,A,B,C)))))",
    "fof(lemma_equalanglesflip,conjecture,(  ! [A,B,C,D,E,F] : ((congA(A,B,C,D,E,F)) => (congA(C,B,A,F,E,D)))))",
    "fof(lemma_supplements2,conjecture,(  ! [A,B,C,D,E,F,J,K,L,P,Q,R] : ((rT(A,B,C,P,Q,R) & congA(A,B,C,J,K,L) & rT(J,K,L,D,E,F)) => (congA(P,Q,R,D,E,F) & congA(D,E,F,P,Q,R)))))",
    "fof(lemma_RTsymmetric,conjecture,(  ! [A,B,C,D,E,F] : ((rT(A,B,C,D,E,F)) => (rT(D,E,F,A,B,C)))))",
    "fof(lemma_RTcongruence,conjecture,(  ! [A,B,C,D,E,F,P,Q,R] : ((rT(A,B,C,D,E,F) & congA(A,B,C,P,Q,R)) => (rT(P,Q,R,D,E,F)))))",
    "fof(lemma_midpointunique,conjecture,(  ! [A,B,C,D] : ((midpoint(A,B,C) & midpoint(A,D,C)) => (eq(B,D)))))",
    "fof(lemma_rightangleNC,conjecture,(  ! [A,B,C] : ((per(A,B,C)) => (nCol(A,B,C)))))",
    "fof(lemma_8_2,conjecture,(  ! [A,B,C] : ((per(A,B,C)) => (per(C,B,A)))))",
    "fof(lemma_rightreverse,conjecture,(  ! [A,B,C,D] : ((per(A,B,C) & betS(A,B,D) & cong(A,B,B,D)) => (cong(A,C,D,C)))))",
    "fof(lemma_8_3,conjecture,(  ! [A,B,C,D] : ((per(A,B,C) & out(B,C,D)) => (per(A,B,D)))))",
    "fof(lemma_equaltorightisright,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((per(A,B,C) & congA(Xa,Xb,Xc,A,B,C)) => (per(Xa,Xb,Xc)))))",
    "fof(lemma_altitudebisectsbase,conjecture,(  ! [A,B,M,P] : ((betS(A,M,B) & cong(A,P,B,P) & per(A,M,P)) => (midpoint(A,M,B)))))",
    "fof(lemma_collinearright,conjecture,(  ! [A,B,C,D] : ((per(A,B,D) & col(A,B,C) & neq(C,B)) => (per(C,B,D)))))",
    "fof(lemma_droppedperpendicularunique,conjecture,(  ! [A,J,M,P] : ((per(A,M,P) & per(A,J,P) & col(A,M,J)) => (eq(M,J)))))",
    "fof(lemma_8_7,conjecture,(  ! [A,B,C] : ((per(C,B,A)) => (nper(A,C,B)))))",
    "fof(lemma_angleorderrespectscongruence,conjecture,(  ! [A,B,C,D,E,F,P,Q,R] : ((ltA(A,B,C,D,E,F) & congA(P,Q,R,D,E,F)) => (ltA(A,B,C,P,Q,R)))))",
    "fof(lemma_angleordertransitive,conjecture,(  ! [A,B,C,D,E,F,P,Q,R] : ((ltA(A,B,C,D,E,F) & ltA(D,E,F,P,Q,R)) => (ltA(A,B,C,P,Q,R)))))",
    "fof(lemma_angleorderrespectscongruence2,conjecture,(  ! [A,B,C,D,E,F,Xa,Xb,Xc] : ((ltA(A,B,C,D,E,F) & congA(Xa,Xb,Xc,A,B,C)) => (ltA(Xa,Xb,Xc,D,E,F)))))",
    "fof(proposition_15,conjecture,(  ! [A,B,C,D,E] : ((betS(A,E,B) & betS(C,E,D) & nCol(A,E,C)) => (congA(A,E,C,D,E,B) & congA(C,E,B,A,E,D)))))",
    "fof(lemma_supplementinequality,conjecture,(  ! [A,B,C,D,F,Xa,Xb,Xc,Xd,Xf] : ((supp(A,B,C,D,F) & supp(Xa,Xb,Xc,Xd,Xf) & ltA(Xa,Xb,Xc,A,B,C)) => (ltA(D,B,F,Xd,Xb,Xf)))))",
    "fof(proposition_05,conjecture,(  ! [A,B,C] : ((isosceles(A,B,C)) => (congA(A,B,C,A,C,B)))))",
    "fof(proposition_05b,conjecture,(  ! [A,B,C,F,G] : ((isosceles(A,B,C) & betS(A,B,F) & betS(A,C,G)) => (congA(C,B,F,B,C,G)))))",
    "fof(proposition_10,conjecture,(  ! [A,B] : ((neq(A,B)) => ? [X] : (betS(A,X,B) & cong(X,A,X,B)))))",
    "fof(lemma_planeseparation,conjecture,(  ! [A,B,C,D,E] : ((oS(C,D,A,B) & tS(D,A,B,E)) => (tS(C,A,B,E)))))",
    "fof(lemma_samesidetransitive,conjecture,(  ! [A,B,P,Q,R] : ((oS(P,Q,A,B) & oS(Q,R,A,B)) => (oS(P,R,A,B)))))",
    "fof(lemma_samesideflip,conjecture,(  ! [A,B,P,Q] : ((oS(P,Q,A,B)) => (oS(P,Q,B,A)))))",
    "fof(lemma_samenotopposite,conjecture,(  ! [A,B,C,D] : ((oS(A,B,C,D)) => (ntS(A,C,D,B)))))",
    "fof(lemma_sameside2,conjecture,(  ! [A,B,C,E,F,G] : ((oS(E,F,A,C) & col(A,B,C) & out(B,F,G)) => (oS(E,G,A,C)))))",
    "fof(proposition_12,conjecture,(  ! [A,B,C] : ((neq(A,B) & nCol(A,B,C)) => ? [X] : (perp_at(C,X,A,B,X)))))",
    "fof(proposition_13,conjecture,(  ! [A,B,C,D] : ((betS(D,B,C) & nCol(A,B,C)) => (rT(C,B,A,A,B,D)))))",
    "fof(proposition_07,conjecture,(  ! [A,B,C,D] : ((neq(A,B) & cong(C,A,D,A) & cong(C,B,D,B) & oS(C,D,A,B)) => (eq(C,D)))))",
    "fof(lemma_crossbar2,conjecture,(  ! [A,G,H,P,S,T] : ((ltA(H,G,A,H,G,P) & oS(A,P,G,H) & out(G,H,S) & out(G,P,T)) => ? [X] : (betS(T,X,S) & out(G,A,X)))))",
    "fof(lemma_angletrichotomy,conjecture,(  ! [A,B,C,D,E,F] : ((ltA(A,B,C,D,E,F)) => (nltA(D,E,F,A,B,C)))))",
    "fof(proposition_06a,conjecture,(  ! [A,B,C] : ((triangle(A,B,C) & congA(A,B,C,A,C,B)) => (nlt(A,C,A,B)))))",
    "fof(proposition_06,conjecture,(  ! [A,B,C] : ((triangle(A,B,C) & congA(A,B,C,A,C,B)) => (cong(A,B,A,C)))))",
    "fof(proposition_08,conjecture,(  ! [A,B,C,D,E,F] : ((triangle(A,B,C) & triangle(D,E,F) & cong(A,B,D,E) & cong(A,C,D,F) & cong(B,C,E,F)) => (congA(B,A,C,E,D,F) & congA(C,B,A,F,E,D) & congA(A,C,B,D,F,E)))))",
    "fof(proposition_09,conjecture,(  ! [A,B,C] : ((nCol(B,A,C)) => ? [X] : (congA(B,A,X,X,A,C) & inAngle(B,A,C,X)))))",
    "fof(proposition_11,conjecture,(  ! [A,B,C] : ((betS(A,C,B)) => ? [X] : (per(A,C,X)))))",
    "fof(lemma_pointreflectionisometry,conjecture,(  ! [A,B,C,P,Q] : ((midpoint(A,B,C) & midpoint(P,B,Q) & neq(A,P)) => (cong(A,P,C,Q)))))",
    "fof(lemma_rightreflection,conjecture,(  ! [A,B,C,E,Xa,Xb,Xc] : ((per(A,B,C) & midpoint(A,E,Xa) & midpoint(B,E,Xb) & midpoint(C,E,Xc)) => (per(Xa,Xb,Xc)))))",
    "fof(lemma_notperp,conjecture,(  ! [A,B,C,P] : ((betS(A,C,B) & nCol(A,B,P)) => ? [X] : (nCol(A,B,X) & oS(X,P,A,B) & nper(A,C,X)))))",
    "fof(proposition_11B,conjecture,(  ! [A,B,C,P] : ((betS(A,C,B) & nCol(A,B,P)) => ? [X] : (per(A,C,X) & tS(X,A,B,P)))))",
    "fof(lemma_linereflectionisometry,conjecture,(  ! [A,B,C,D,E,F] : ((per(B,A,C) & per(A,B,D) & betS(C,A,E) & betS(D,B,F) & cong(A,C,A,E) & cong(B,D,B,F)) => (cong(C,D,E,F)))))",
    "fof(lemma_10_12,conjecture,(  ! [A,B,C,H] : ((per(A,B,C) & per(A,B,H) & cong(B,C,B,H)) => (cong(A,C,A,H)))))",
    "fof(lemma_erectedperpendicularunique,conjecture,(  ! [A,B,C,E] : ((per(A,B,C) & per(A,B,E) & oS(C,E,A,B)) => (out(B,C,E)))))",
    "fof(proposition_14,conjecture,(  ! [A,B,C,D,E] : ((rT(A,B,C,D,B,E) & out(B,C,D) & tS(E,D,B,A)) => (supp(A,B,C,D,E) & betS(A,B,E)))))",
    "fof(proposition_16,conjecture,(  ! [A,B,C,D] : ((triangle(A,B,C) & betS(B,C,D)) => (ltA(B,A,C,A,C,D) & ltA(C,B,A,A,C,D)))))",
    "fof(proposition_17,conjecture,(  ! [A,B,C] : ((triangle(A,B,C)) => ? [X,Y,Z] : (sumA(A,B,C,B,C,A,X,Y,Z)))))",
    "fof(proposition_18,conjecture,(  ! [A,B,C] : ((triangle(A,B,C) & lt(A,B,A,C)) => (ltA(B,C,A,A,B,C)))))",
    "fof(proposition_19,conjecture,(  ! [A,B,C] : ((triangle(A,B,C) & ltA(B,C,A,A,B,C)) => (lt(A,B,A,C)))))",
    "fof(proposition_20,conjecture,(  ! [A,B,C] : ((triangle(A,B,C)) => (tG(B,A,A,C,B,C)))))",
    "fof(lemma_together,conjecture,(  ! [A,B,C,D,F,G,P,Q,Xa,Xb,Xc] : ((tG(A,Xa,B,Xb,C,Xc) & cong(D,F,A,Xa) & cong(F,G,B,Xb) & betS(D,F,G) & cong(P,Q,C,Xc)) => (lt(P,Q,D,G) & neq(A,Xa) & neq(B,Xb) & neq(C,Xc)))))",
    "fof(lemma_together2,conjecture,(  ! [A,B,C,F,G,M,N,Xa,Xb,Xc] : ((tG(A,Xa,C,Xc,B,Xb) & cong(F,G,B,Xb) & out(F,G,M) & cong(F,M,A,Xa) & out(G,F,N) & cong(G,N,C,Xc)) => (out(M,F,N)))))",
    "fof(lemma_TGsymmetric,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((tG(A,Xa,B,Xb,C,Xc)) => (tG(B,Xb,A,Xa,C,Xc)))))",
    "fof(lemma_TGflip,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((tG(A,Xa,B,Xb,C,Xc)) => (tG(Xa,A,B,Xb,C,Xc) & tG(A,Xa,B,Xb,Xc,C)))))",
    "fof(lemma_21helper,conjecture,(  ! [A,B,C,E] : ((tG(B,A,A,E,B,E) & betS(A,E,C)) => (tT(B,A,A,C,B,E,E,C)))))",
    "fof(lemma_TTorder,conjecture,(  ! [A,B,C,D,E,F,G,H] : ((tT(A,B,C,D,E,F,G,H)) => (tT(C,D,A,B,E,F,G,H)))))",
    "fof(lemma_TTflip,conjecture,(  ! [A,B,C,D,E,F,G,H] : ((tT(A,B,C,D,E,F,G,H)) => (tT(B,A,D,C,E,F,G,H)))))",
    "fof(lemma_TTtransitive,conjecture,(  ! [A,B,C,D,E,F,G,H,P,Q,R,S] : ((tT(A,B,C,D,E,F,G,H) & tT(E,F,G,H,P,Q,R,S)) => (tT(A,B,C,D,P,Q,R,S)))))",
    "fof(lemma_TTflip2,conjecture,(  ! [A,B,C,D,E,F,G,H] : ((tT(A,B,C,D,E,F,G,H)) => (tT(A,B,C,D,H,G,F,E)))))",
    "fof(proposition_21,conjecture,(  ! [A,B,C,D,E] : ((triangle(A,B,C) & betS(A,E,C) & betS(B,D,E)) => (tT(B,A,A,C,B,D,D,C) & ltA(B,A,C,B,D,C)))))",
    "fof(proposition_22,conjecture,(  ! [A,B,C,E,F,Xa,Xb,Xc] : ((tG(A,Xa,B,Xb,C,Xc) & tG(A,Xa,C,Xc,B,Xb) & tG(B,Xb,C,Xc,A,Xa) & neq(F,E)) => ? [X,Y] : (cong(F,X,B,Xb) & cong(F,Y,A,Xa) & cong(X,Y,C,Xc) & out(F,E,X) & triangle(F,X,Y)))))",
    "fof(lemma_Euclid4,conjecture,(  ! [A,B,C,Xa,Xb,Xc] : ((per(A,B,C) & per(Xa,Xb,Xc)) => (congA(A,B,C,Xa,Xb,Xc)))))",
    "fof(lemma_legsmallerhypotenuse,conjecture,(  ! [A,B,C] : ((per(A,B,C)) => (lt(A,B,A,C) & lt(B,C,A,C)))))",
    "fof(proposition_23,conjecture,(  ! [A,B,C,D,E] : ((neq(A,B) & nCol(D,C,E)) => ? [X,Y] : (out(A,B,Y) & congA(X,A,Y,D,C,E)))))",
    "fof(proposition_23B,conjecture,(  ! [A,B,C,D,E,P] : ((neq(A,B) & nCol(D,C,E) & nCol(A,B,P)) => ? [X,Y] : (out(A,B,Y) & congA(X,A,Y,D,C,E) & tS(X,A,B,P)))))",
    "fof(proposition_23C,conjecture,(  ! [A,B,C,D,E,P] : ((neq(A,B) & nCol(D,C,E) & nCol(A,B,P)) => ? [X,Y] : (out(A,B,Y) & congA(X,A,Y,D,C,E) & oS(X,P,A,B)))))",
    "fof(proposition_24,conjecture,(  ! [A,B,C,D,E,F] : ((triangle(A,B,C) & triangle(D,E,F) & cong(A,B,D,E) & cong(A,C,D,F) & ltA(E,D,F,B,A,C)) => (lt(E,F,B,C)))))",
    "fof(lemma_angletrichotomy2,conjecture,(  ! [A,B,C,D,E,F] : ((nCol(A,B,C) & nCol(D,E,F) & ncongA(A,B,C,D,E,F) & nltA(D,E,F,A,B,C)) => (ltA(A,B,C,D,E,F)))))",
    "fof(proposition_25,conjecture,(  ! [A,B,C,D,E,F] : ((triangle(A,B,C) & triangle(D,E,F) & cong(A,B,D,E) & cong(A,C,D,F) & lt(E,F,B,C)) => (ltA(E,D,F,B,A,C)))))",
    "fof(proposition_26A,conjecture,(  ! [A,B,C,D,E,F] : ((triangle(A,B,C) & triangle(D,E,F) & congA(A,B,C,D,E,F) & congA(B,C,A,E,F,D) & cong(B,C,E,F)) => (cong(A,B,D,E) & cong(A,C,D,F) & congA(B,A,C,E,D,F)))))",
    "fof(lemma_26helper,conjecture,(  ! [A,B,C,D,E,F] : ((triangle(A,B,C) & congA(A,B,C,D,E,F) & congA(B,C,A,E,F,D) & cong(A,B,D,E)) => (nlt(E,F,B,C)))))",
    "fof(proposition_26B,conjecture,(  ! [A,B,C,D,E,F] : ((triangle(A,B,C) & triangle(D,E,F) & congA(A,B,C,D,E,F) & congA(B,C,A,E,F,D) & cong(A,B,D,E)) => (cong(B,C,E,F) & cong(A,C,D,F) & congA(B,A,C,E,D,F)))))",
    "fof(lemma_parallelsymmetric,conjecture,(  ! [A,B,C,D] : ((par(A,B,C,D)) => (par(C,D,A,B)))))",
    "fof(lemma_paralleldef2A,conjecture,(  ! [A,B,C,D] : ((tP(A,B,C,D)) => (par(A,B,C,D)))))",
    "fof(lemma_parallelcollinear1,conjecture,(  ! [A,B,C,Xc,Xd] : ((tP(A,B,Xc,Xd) & betS(C,Xc,Xd)) => (tP(A,B,C,Xd)))))",
    "fof(lemma_tarskiparallelflip,conjecture,(  ! [A,B,C,D] : ((tP(A,B,C,D)) => (tP(B,A,C,D) & tP(A,B,D,C) & tP(B,A,D,C)))))",
    "fof(lemma_parallelcollinear2,conjecture,(  ! [A,B,C,Xc,Xd] : ((tP(A,B,Xc,Xd) & betS(Xc,C,Xd)) => (tP(A,B,C,Xd)))))",
    "fof(lemma_parallelcollinear,conjecture,(  ! [A,B,C,Xc,Xd] : ((tP(A,B,Xc,Xd) & col(Xc,Xd,C) & neq(C,Xd)) => (tP(A,B,C,Xd)))))",
    "fof(lemma_paralleldef2B,conjecture,(  ! [A,B,C,D] : ((par(A,B,C,D)) => (tP(A,B,C,D)))))",
    "fof(lemma_parallelflip,conjecture,(  ! [A,B,C,D] : ((par(A,B,C,D)) => (par(B,A,C,D) & par(A,B,D,C) & par(B,A,D,C)))))",
    "fof(lemma_collinearparallel,conjecture,(  ! [A,B,C,Xc,Xd] : ((par(A,B,Xc,Xd) & col(Xc,Xd,C) & neq(C,Xd)) => (par(A,B,C,Xd)))))",
    "fof(lemma_parallelNC,conjecture,(  ! [A,B,C,D] : ((par(A,B,C,D)) => (nCol(A,B,C) & nCol(A,C,D) & nCol(B,C,D) & nCol(A,B,D)))))",
    "fof(lemma_collinearparallel2,conjecture,(  ! [A,B,C,D,E,F] : ((par(A,B,C,D) & col(C,D,E) & col(C,D,F) & neq(E,F)) => (par(A,B,E,F)))))",
    "fof(proposition_27,conjecture,(  ! [A,B,C,D,E,F] : ((betS(A,E,B) & betS(C,F,D) & congA(A,E,F,E,F,D) & tS(A,E,F,D)) => (par(A,B,C,D)))))",
    "fof(proposition_27B,conjecture,(  ! [A,D,E,F] : ((congA(A,E,F,E,F,D) & tS(A,E,F,D)) => (par(A,E,F,D)))))",
    "fof(proposition_28A,conjecture,(  ! [A,B,C,D,E,G,H] : ((betS(A,G,B) & betS(C,H,D) & betS(E,G,H) & congA(E,G,B,G,H,D) & oS(B,D,G,H)) => (par(A,B,C,D)))))",
    "fof(proposition_28B,conjecture,(  ! [A,B,C,D,G,H] : ((betS(A,G,B) & betS(C,H,D) & rT(B,G,H,G,H,D) & oS(B,D,G,H)) => (par(A,B,C,D)))))",
    "fof(proposition_28C,conjecture,(  ! [B,D,G,H] : ((rT(B,G,H,G,H,D) & oS(B,D,G,H)) => (par(G,B,H,D)))))",
    "fof(proposition_28D,conjecture,(  ! [B,D,E,G,H] : ((betS(E,G,H) & congA(E,G,B,G,H,D) & oS(B,D,G,H)) => (par(G,B,H,D)))))",
    "fof(proposition_31,conjecture,(  ! [A,B,C,D] : ((betS(B,D,C) & nCol(B,C,A)) => ? [X,Y,Z] : (betS(X,A,Y) & congA(Y,A,D,A,D,B) & congA(Y,A,D,B,D,A) & congA(D,A,Y,B,D,A) & congA(X,A,D,A,D,C) & congA(X,A,D,C,D,A) & congA(D,A,X,C,D,A) & par(X,Y,B,C) & cong(X,A,D,C) & cong(A,Y,B,D) & cong(A,Z,Z,D) & cong(X,Z,Z,C) & cong(B,Z,Z,Y) & betS(X,Z,C) & betS(B,Z,Y) & betS(A,Z,D)))))",
    "fof(proposition_31short,conjecture,(  ! [A,B,C,D] : ((betS(B,D,C) & nCol(B,C,A)) => ? [X,Y,Z] : (betS(X,A,Y) & congA(X,A,D,A,D,C) & par(X,Y,B,C) & betS(X,Z,C) & betS(A,Z,D)))))",
    "fof(proposition_29,conjecture,(  ! [A,B,C,D,E,G,H] : ((par(A,B,C,D) & betS(A,G,B) & betS(C,H,D) & betS(E,G,H) & tS(A,G,H,D)) => (congA(A,G,H,G,H,D) & congA(E,G,B,G,H,D) & rT(B,G,H,G,H,D)))))",
    "fof(proposition_29B,conjecture,(  ! [A,D,G,H] : ((par(A,G,H,D) & tS(A,G,H,D)) => (congA(A,G,H,G,H,D)))))",
    "fof(proposition_29C,conjecture,(  ! [B,D,E,G,H] : ((par(G,B,H,D) & oS(B,D,G,H) & betS(E,G,H)) => (congA(E,G,B,G,H,D) & rT(B,G,H,G,H,D)))))",
    "fof(lemma_crossimpliesopposite,conjecture,(  ! [A,B,C,D] : ((cR(A,B,C,D) & nCol(A,C,D)) => (tS(A,C,D,B) & tS(A,D,C,B) & tS(B,C,D,A) & tS(B,D,C,A)))))",
    "fof(lemma_crisscross,conjecture,(  ! [A,B,C,D] : ((par(A,C,B,D) & ncR(A,B,C,D)) => (cR(A,D,B,C)))))",
    "fof(proposition_30A,conjecture,(  ! [A,B,C,D,E,F,G,H,K] : ((par(A,B,E,F) & par(C,D,E,F) & betS(G,H,K) & betS(A,G,B) & betS(E,H,F) & betS(C,K,D) & tS(A,G,H,F) & tS(F,H,K,C)) => (par(A,B,C,D)))))",
    "fof(lemma_30helper,conjecture,(  ! [A,B,E,F,G,H] : ((par(A,B,E,F) & betS(A,G,B) & betS(E,H,F) & ncR(A,F,G,H)) => (cR(A,E,G,H)))))",
    "fof(proposition_30,conjecture,(  ! [A,B,C,D,E,F,G,H,K] : ((par(A,B,E,F) & par(C,D,E,F) & betS(G,H,K) & col(A,B,G) & col(E,F,H) & col(C,D,K) & neq(A,G) & neq(E,H) & neq(C,K)) => (par(A,B,C,D)))))",
    "fof(proposition_30B,conjecture,(  ! [A,B,C,D,E,F,G,H,K] : ((par(A,B,E,F) & par(C,D,E,F) & betS(G,K,H) & betS(A,G,B) & betS(E,H,F) & betS(C,K,D) & tS(A,G,H,F) & tS(C,K,H,F)) => (par(A,B,C,D)))))",
    "fof(proposition_32,conjecture,(  ! [A,B,C,D] : ((triangle(A,B,C) & betS(B,C,D)) => (sumA(C,A,B,A,B,C,A,C,D)))))",
    "fof(proposition_33,conjecture,(  ! [A,B,C,D,M] : ((par(A,B,C,D) & cong(A,B,C,D) & betS(A,M,D) & betS(B,M,C)) => (par(A,C,B,D) & cong(A,C,B,D)))))",
    "fof(lemma_diagonalsmeet,conjecture,(  ! [A,B,C,D] : ((pG(A,B,C,D)) => ? [X] : (betS(A,X,C) & betS(B,X,D)))))",
    "fof(lemma_TCreflexive,conjecture,(  ! [A,B,C] : ((triangle(A,B,C)) => (cong_3(A,B,C,A,B,C)))))",
    "fof(lemma_EFreflexive,conjecture,(  ! [Xa,Xb,Xc,Xd,Xp] : ((betS(Xa,Xp,Xc) & betS(Xb,Xp,Xd) & nCol(Xa,Xb,Xc)) => (eF(Xa,Xb,Xc,Xd,Xa,Xb,Xc,Xd)))))",
    "fof(lemma_parallelPasch,conjecture,(  ! [A,B,C,D,E] : ((pG(A,B,C,D) & betS(A,D,E)) => ? [X] : (betS(B,X,E) & betS(C,X,D)))))",
    "fof(lemma_parallelbetween,conjecture,(  ! [B,H,K,L,M] : ((betS(H,B,K) & par(M,B,H,L) & col(L,M,K)) => (betS(L,M,K)))))",
    "fof(proposition_34,conjecture,(  ! [A,B,C,D] : ((pG(A,C,D,B)) => (cong(A,B,C,D) & cong(A,C,B,D) & congA(C,A,B,B,D,C) & congA(A,B,D,D,C,A) & cong_3(C,A,B,B,D,C)))))",
    "fof(lemma_diagonalsbisect,conjecture,(  ! [A,B,C,D] : ((pG(A,B,C,D)) => ? [X] : (midpoint(A,X,C) & midpoint(B,X,D)))))",
    "fof(lemma_trapezoiddiagonals,conjecture,(  ! [A,B,C,D,E] : ((pG(A,B,C,D) & betS(A,E,D)) => ? [X] : (betS(B,X,D) & betS(C,X,E)))))",
    "fof(lemma_ETreflexive,conjecture,(  ! [A,B,C] : ((triangle(A,B,C)) => (eT(A,B,C,A,B,C)))))",
    "fof(lemma_PGflip,conjecture,(  ! [A,B,C,D] : ((pG(A,B,C,D)) => (pG(B,A,D,C)))))",
    "fof(lemma_PGsymmetric,conjecture,(  ! [A,B,C,D] : ((pG(A,B,C,D)) => (pG(C,D,A,B)))))",
    "fof(lemma_PGrotate,conjecture,(  ! [A,B,C,D] : ((pG(A,B,C,D)) => (pG(B,C,D,A)))))",
    "fof(proposition_33B,conjecture,(  ! [A,B,C,D] : ((par(A,B,C,D) & cong(A,B,C,D) & oS(A,C,B,D)) => (par(A,C,B,D) & cong(A,C,B,D)))))",
    "fof(lemma_Playfairhelper,conjecture,(  ! [A,B,C,D,E] : ((par(A,B,C,D) & par(A,B,C,E) & cR(A,D,B,C) & cR(A,E,B,C)) => (col(C,D,E)))))",
    "fof(lemma_Playfairhelper2,conjecture,(  ! [A,B,C,D,E] : ((par(A,B,C,D) & par(A,B,C,E) & cR(A,D,B,C)) => (col(C,D,E)))))",
    "fof(lemma_Playfair,conjecture,(  ! [A,B,C,D,E] : ((par(A,B,C,D) & par(A,B,C,E)) => (col(C,D,E)))))",
    "fof(lemma_triangletoparallelogram,conjecture,(  ! [A,C,D,E,F] : ((par(D,C,E,F) & col(E,F,A)) => ? [X] : (pG(A,X,C,D) & col(E,F,X)))))",
    "fof(lemma_35helper,conjecture,(  ! [A,B,C,D,E,F] : ((pG(A,B,C,D) & pG(E,B,C,F) & betS(A,D,F) & col(A,E,F)) => (betS(A,E,F)))))",
    "fof(proposition_35A,conjecture,(  ! [A,B,C,D,E,F] : ((pG(A,B,C,D) & pG(E,B,C,F) & betS(A,D,F) & col(A,E,F)) => (eF(A,B,C,D,E,B,C,F)))))",
    "fof(proposition_35,conjecture,(  ! [A,B,C,D,E,F] : ((pG(A,B,C,D) & pG(E,B,C,F) & col(A,D,E) & col(A,D,F)) => (eF(A,B,C,D,E,B,C,F)))))",
    "fof(proposition_36A,conjecture,(  ! [A,B,C,D,E,F,G,H,M] : ((pG(A,B,C,D) & pG(E,F,G,H) & col(A,D,E) & col(A,D,H) & col(B,C,F) & col(B,C,G) & cong(B,C,F,G) & betS(B,M,H) & betS(C,M,E)) => (eF(A,B,C,D,E,F,G,H)))))",
    "fof(proposition_36,conjecture,(  ! [A,B,C,D,E,F,G,H] : ((pG(A,B,C,D) & pG(E,F,G,H) & col(A,D,E) & col(A,D,H) & col(B,C,F) & col(B,C,G) & cong(B,C,F,G)) => (eF(A,B,C,D,E,F,G,H)))))",
    "fof(proposition_37,conjecture,(  ! [A,B,C,D] : ((par(A,D,B,C)) => (eT(A,B,C,D,B,C)))))",
    "fof(proposition_38,conjecture,(  ! [A,B,C,D,E,F,P,Q] : ((par(P,Q,B,C) & col(P,Q,A) & col(P,Q,D) & cong(B,C,E,F) & col(B,C,E) & col(B,C,F)) => (eT(A,B,C,D,E,F)))))",
    "fof(proposition_39A,conjecture,(  ! [A,B,C,D,M] : ((triangle(A,B,C) & eT(A,B,C,D,B,C) & betS(A,M,C) & out(B,D,M)) => (par(A,D,B,C)))))",
    "fof(proposition_39,conjecture,(  ! [A,B,C,D] : ((triangle(A,B,C) & triangle(D,B,C) & oS(A,D,B,C) & eT(A,B,C,D,B,C) & neq(A,D)) => (par(A,D,B,C)))))",
    "fof(proposition_40,conjecture,(  ! [A,B,C,D,E,H] : ((cong(B,C,H,E) & eT(A,B,C,D,H,E) & triangle(A,B,C) & triangle(D,H,E) & col(B,C,H) & col(B,C,E) & oS(A,D,B,C) & neq(A,D)) => (par(A,D,B,C)))))",
    "fof(proposition_41,conjecture,(  ! [A,B,C,D,E] : ((pG(A,B,C,D) & col(A,D,E)) => (eT(A,B,C,E,B,C)))))",
    "fof(proposition_42,conjecture,(  ! [A,B,C,D,E,J,K] : ((triangle(A,B,C) & nCol(J,D,K) & midpoint(B,E,C)) => ? [X,Z] : (pG(X,E,C,Z) & eF(A,B,E,C,X,E,C,Z) & congA(C,E,X,J,D,K) & col(X,Z,A)))))",
    "fof(proposition_42B,conjecture,(  ! [B,C,D,E,J,K,R,Xa,Xb,Xc,Xe] : ((triangle(Xa,Xb,Xc) & midpoint(Xb,Xe,Xc) & nCol(J,D,K) & midpoint(B,E,C) & cong(E,C,Xe,Xc) & nCol(R,E,C)) => ? [X,Z] : (pG(X,E,C,Z) & eF(Xa,Xb,Xe,Xc,X,E,C,Z) & congA(C,E,X,J,D,K) & oS(R,X,E,C)))))",
    "fof(proposition_43,conjecture,(  ! [A,B,C,D,E,F,G,H,K] : ((pG(A,B,C,D) & betS(A,H,D) & betS(A,E,B) & betS(D,F,C) & betS(B,G,C) & betS(A,K,C) & pG(E,A,H,K) & pG(G,K,F,C)) => (eF(K,G,B,E,D,F,K,H)))))",
    "fof(proposition_43B,conjecture,(  ! [A,B,C,D,E,F,G,H,K] : ((pG(A,B,C,D) & betS(A,H,D) & betS(A,E,B) & betS(D,F,C) & betS(B,G,C) & pG(E,A,H,K) & pG(G,K,F,C)) => (pG(E,K,G,B)))))",
    "fof(proposition_44A,conjecture,(  ! [A,B,D,E,F,G,J,N] : ((pG(B,E,F,G) & congA(E,B,G,J,D,N) & betS(A,B,E)) => ? [X,Y] : (pG(A,B,X,Y) & congA(A,B,X,J,D,N) & eF(B,E,F,G,Y,X,B,A) & betS(G,B,X)))))",
    "fof(proposition_44,conjecture,(  ! [A,B,D,J,N,R,Xa,Xb,Xc] : ((triangle(Xa,Xb,Xc) & nCol(J,D,N) & nCol(A,B,R)) => ? [X,Y,Z] : (pG(A,B,X,Y) & congA(A,B,X,J,D,N) & eF(Xa,Xb,Z,Xc,A,B,X,Y) & midpoint(Xb,Z,Xc) & tS(X,A,B,R)))))",
    "fof(proposition_45,conjecture,(  ! [A,B,C,D,E,J,K,N,O,R,S] : ((nCol(J,E,N) & nCol(A,B,D) & nCol(C,B,D) & betS(A,O,C) & betS(B,O,D) & neq(R,K) & nCol(K,R,S)) => ? [X,Z,U] : (pG(X,K,Z,U) & congA(X,K,Z,J,E,N) & eF(X,K,Z,U,A,B,C,D) & out(K,R,Z) & oS(X,S,K,Z)))))",
    "fof(proposition_46,conjecture,(  ! [A,B,R] : ((neq(A,B) & nCol(A,B,R)) => ? [X,Y] : (sQ(A,B,X,Y) & tS(Y,A,B,R) & pG(A,B,X,Y)))))",
    "fof(lemma_righttogether,conjecture,(  ! [A,B,C,G] : ((per(G,A,B) & per(B,A,C) & tS(G,B,A,C)) => (rT(G,A,B,B,A,C) & betS(G,A,C)))))",
    "fof(lemma_twoperpsparallel,conjecture,(  ! [A,B,C,D] : ((per(A,B,C) & per(B,C,D) & oS(A,D,B,C)) => (par(A,B,C,D)))))",
    "fof(lemma_squareparallelogram,conjecture,(  ! [A,B,C,D] : ((sQ(A,B,C,D)) => (pG(A,B,C,D)))))",
    "fof(lemma_squareunique,conjecture,(  ! [A,B,C,D,E] : ((sQ(A,B,C,D) & sQ(A,B,C,E)) => (eq(E,D)))))",
    "fof(lemma_altitudeofrighttriangle,conjecture,(  ! [A,B,C,M,Xp] : ((per(B,A,C) & per(A,M,Xp) & col(B,C,Xp) & col(B,C,M)) => (betS(B,M,C)))))",
    "fof(lemma_squareflip,conjecture,(  ! [A,B,C,D] : ((sQ(A,B,C,D)) => (sQ(B,A,D,C)))))",
    "fof(proposition_47A,conjecture,(  ! [A,B,C,D,E] : ((triangle(A,B,C) & per(B,A,C) & sQ(B,C,E,D) & tS(D,C,B,A)) => ? [X,Y] : (pG(B,X,Y,D) & betS(B,X,C) & pG(X,C,E,Y) & betS(D,Y,E) & betS(Y,X,A) & per(D,Y,A)))))",
    "fof(lemma_angleaddition,conjecture,(  ! [A,B,C,D,E,F,P,Q,R,Xa,Xb,Xc,Xd,Xe,Xf,Xp,Xq,Xr] : ((sumA(A,B,C,D,E,F,P,Q,R) & congA(A,B,C,Xa,Xb,Xc) & congA(D,E,F,Xd,Xe,Xf) & sumA(Xa,Xb,Xc,Xd,Xe,Xf,Xp,Xq,Xr)) => (congA(P,Q,R,Xp,Xq,Xr)))))",
    "fof(proposition_47B,conjecture,(  ! [A,B,C,D,E,F,G] : ((triangle(A,B,C) & per(B,A,C) & sQ(A,B,F,G) & tS(G,B,A,C) & sQ(B,C,E,D) & tS(D,C,B,A)) => ? [X,Y] : (pG(B,X,Y,D) & betS(B,X,C) & pG(X,C,E,Y) & betS(D,Y,E) & betS(Y,X,A) & per(D,Y,A) & eF(A,B,F,G,B,X,Y,D)))))",
    "fof(proposition_47,conjecture,(  ! [A,B,C,D,E,F,G,H,K] : ((triangle(A,B,C) & per(B,A,C) & sQ(A,B,F,G) & tS(G,B,A,C) & sQ(A,C,K,H) & tS(H,C,A,B) & sQ(B,C,E,D) & tS(D,C,B,A)) => ? [X,Y] : (pG(B,X,Y,D) & betS(B,X,C) & pG(X,C,E,Y) & betS(D,Y,E) & eF(A,B,F,G,B,X,Y,D) & eF(A,C,K,H,X,C,E,Y)))))",
    "fof(lemma_rectangleparallelogram,conjecture,(  ! [A,B,C,D] : ((rE(A,B,C,D)) => (pG(A,B,C,D)))))",
    "fof(lemma_supplementofright,conjecture,(  ! [A,B,C,D,F] : ((supp(A,B,C,D,F) & per(A,B,C)) => (per(F,B,D) & per(D,B,F)))))",
    "fof(lemma_PGrectangle,conjecture,(  ! [A,B,C,D] : ((pG(A,C,D,B) & per(B,A,C)) => (rE(A,C,D,B)))))",
    "fof(lemma_squarerectangle,conjecture,(  ! [A,B,C,D] : ((sQ(A,B,C,D)) => (rE(A,B,C,D)))))",
    "fof(lemma_rectanglereverse,conjecture,(  ! [A,B,C,D] : ((rE(A,B,C,D)) => (rE(D,C,B,A)))))",
    "fof(lemma_rectanglerotate,conjecture,(  ! [A,B,C,D] : ((rE(A,B,C,D)) => (rE(B,C,D,A)))))",
    "fof(lemma_squaresequal,conjecture,(  ! [A,B,C,D,Xa,Xb,Xc,Xd] : ((cong(A,B,Xa,Xb) & sQ(A,B,C,D) & sQ(Xa,Xb,Xc,Xd)) => (eF(A,B,C,D,Xa,Xb,Xc,Xd)))))",
    "fof(lemma_paste5,conjecture,(  ! [B,C,D,E,L,M,Xb,Xc,Xd,Xe,Xl,Xm] : ((eF(B,M,L,D,Xb,Xm,Xl,Xd) & eF(M,C,E,L,Xm,Xc,Xe,Xl) & betS(B,M,C) & betS(Xb,Xm,Xc) & betS(E,L,D) & betS(Xe,Xl,Xd) & rE(M,C,E,L) & rE(Xm,Xc,Xe,Xl)) => (eF(B,C,E,D,Xb,Xc,Xe,Xd)))))",
    "fof(proposition_48A,conjecture,(  ! [A,B,C,D,Xa,Xb,Xc,Xd] : ((sQ(A,B,C,D) & sQ(Xa,Xb,Xc,Xd) & eF(A,B,C,D,Xa,Xb,Xc,Xd)) => (cong(A,B,Xa,Xb)))))",
    "fof(proposition_48,conjecture,(  ! [A,B,C,D,E,F,G,H,K,L,M] : ((triangle(A,B,C) & sQ(A,B,F,G) & sQ(A,C,K,H) & sQ(B,C,E,D) & betS(B,M,C) & betS(E,L,D) & eF(A,B,F,G,B,M,L,D) & eF(A,C,K,H,M,C,E,L) & rE(M,C,E,L)) => (per(B,A,C)))))",
    "fof(lemma_collinearmidpoint,conjecture,(  ! [A,B,M] : ((col(A,B,M) & neq(A,B) & cong(A,M,M,B)) => (betS(A,M,B) & midpoint(A,M,B)))))",
    "fof(proposition_III_01,conjecture,(  ! [A,B,C,D,E,F,G,J,P,Q] : ((cI(J,G,P,Q) & onCirc(A,J) & onCirc(B,J) & neq(A,B) & midpoint(A,D,B) & onCirc(C,J) & onCirc(E,J) & perp_at(C,E,A,B,D) & oS(C,G,A,B) & midpoint(C,F,E) & betS(C,D,E)) => (eq(G,F)))))",
    "fof(lemma_centerunique,conjecture,(  ! [F,G,J,P,Q,Xp,Xq] : ((cI(J,F,P,Q) & cI(J,G,Xp,Xq)) => (eq(F,G)))))",
    "fof(lemma_radiusdetermined,conjecture,(  ! [F,G,J,P,Q,Xp,Xq] : ((cI(J,F,P,Q) & cI(J,G,Xp,Xq) & neq(P,Q) & neq(Xp,Xq)) => (cong(P,Q,Xp,Xq)))))",
    "fof(lemma_radiiequal,conjecture,(  ! [A,B,C,J,P,Q] : ((cI(J,C,P,Q) & onCirc(A,J) & onCirc(B,J)) => (cong(C,A,C,B)))))",
    "fof(proposition_III_02,conjecture,(  ! [A,B,D,E,J,P,Q] : ((cI(J,D,P,Q) & onCirc(A,J) & onCirc(B,J) & betS(A,E,B)) => (inCirc(E,J)))))",
    "fof(proposition_III_03A,conjecture,(  ! [A,B,C,D,E,F,J] : ((cI(J,E,E,A) & onCirc(C,J) & onCirc(D,J) & onCirc(A,J) & onCirc(B,J) & midpoint(A,F,B) & nCol(A,B,E)) => (per(A,F,E) & per(B,F,E)))))",
    "fof(proposition_III_03B,conjecture,(  ! [A,B,C,D,E,F,J] : ((cI(J,E,E,A) & onCirc(C,J) & onCirc(D,J) & onCirc(A,J) & onCirc(B,J) & per(A,F,E) & per(B,F,E) & betS(A,F,B) & nCol(A,B,E)) => (midpoint(A,F,B)))))"
    //"fof(proposition_III_04,conjecture,(  ! [A,B,C,D,E,F,J] : ((cI(J,F,F,A) & onCirc(A,J) & onCirc(B,J) & onCirc(C,J) & onCirc(D,J) & nCol(A,C,F) & nCol(B,D,F) & cut(A,B,C,D,E)) => (n(midpoint(B,E,D) & midpoint(A,E,C))))))",
    //"fof(proposition_III_05,conjecture,(  ! [C,E,H,J,K] : ((cI(J,E,E,C) & cI(K,H,H,C) & (J,K,C)) => (neq(E,H)))))",
    //"fof(proposition_III_06,conjecture,(  ! [C,E,H,J,K] : ((cI(J,E,E,C) & cI(K,H,H,C) & (J,K,C)) => (neq(E,H)))))"
};


