fof(ax_is_image_spec_in_gen_1,axiom,(![M,P1,P,A,B]:((is_image_spec_in_gen(M,P1,P,A,B))=>((A!=B&is_image_spec_in(M,P1,P,A,B))|(A=B&A=M&is_midpoint(M,P,P1)))))).
fof(ax_is_image_spec_in_gen_2,axiom,(![M,P1,P,A,B]:((A!=B&is_image_spec_in(M,P1,P,A,B))=>is_image_spec_in_gen(M,P1,P,A,B)))).
fof(ax_is_image_spec_in_gen_3,axiom,(![M,P1,P]:((is_midpoint(M,P,P1))=>is_image_spec_in_gen(M,P1,P,M,M)))).
fof(ax_is_image_spec_in_1,axiom,(![M,P1,P,A,B]:((A!=B&is_image_spec_in(M,P1,P,A,B))=>((is_midpoint(M,P,P1)&col(A,B,M)&perp(A,B,P,P1))|(is_midpoint(M,P,P1)&col(A,B,M)&P=P1))))).
fof(ax_is_image_spec_in_2,axiom,(![M,P1,P,A,B]:((A!=B&is_midpoint(M,P,P1)&col(A,B,M)&perp(A,B,P,P1))=>(is_image_spec_in(M,P1,P,A,B))))).
fof(ax_is_image_spec_in_3,axiom,(![M,P,A,B]:((A!=B&is_midpoint(M,P,P)&col(A,B,M))=>(is_image_spec_in(M,P,P,A,B))))).
fof(ax_10_3_3,axiom,(![P,P1,A,B]:((is_image(P1,P,A,B))=>((A!=B&is_image_spec(P1,P,A,B))|(A=B&is_midpoint(A,P,P1)))))).
fof(ax_10_3_4_1,axiom,(![P,P1,A,B]:((A!=B&is_image_spec(P1,P,A,B))=>is_image(P1,P,A,B)))).
fof(ax_10_3_4_2,axiom,(![P,P1,A]:(is_midpoint(A,P,P1)=>is_image(P1,P,A,A)))).
fof(ax_10_3_1,axiom,(![P,P1,A,B]:((A!=B&is_image_spec(P1,P,A,B))=>((?[X]:(is_midpoint(X,P,P1)&point_on_line(X,A,B)&perp(A,B,P,P1)))|(?[X]:(is_midpoint(X,P,P1)&point_on_line(X,A,B)&P=P1)))))).
fof(ax_10_3_2_1,axiom,(![P,P1,A,B,X]:((A!=B&is_midpoint(X,P,P1)&point_on_line(X,A,B)&perp(A,B,P,P1))=>is_image_spec(P1,P,A,B)))).
fof(ax_10_3_2_2,axiom,(![P,A,B,X]:((A!=B&is_midpoint(X,P,P)&point_on_line(X,A,B))=>is_image_spec(P,P,A,B)))).
fof(ax_7_1,axiom,(![A,M,B]:((is_midpoint(M,A,B))=>(bet(A,M,B)&cong(M,A,M,B))))).
fof(ax_7_2,axiom,(![A,M,B]:((bet(A,M,B)&cong(M,A,M,B))=>is_midpoint(M,A,B)))).
