fof(th_8_18_1,axiom,(![A,B,C]:(ncol(A,B,C)=>(?[X]:(col(A,B,X)&perp(A,B,C,X)))))).
fof(th_8_20_2,axiom,(![A,B,C,P,C1,C2]:((per(A,B,C)&is_symmetric(C,C1,A)&is_symmetric(C,C2,B)&is_midpoint(P,C1,C2)&B!=C)=>A!=P))).
fof(th_8_20_1,axiom,(![A,B,C,P,C1,C2]:((per(A,B,C)&is_symmetric(C,C1,A)&is_symmetric(C,C2,B)&is_midpoint(P,C1,C2))=>per(B,A,P)))).
fof(perp_col0,axiom,![A,B,C,D,X,Y]:((perp(A,B,C,D)&X!=Y&col(A,B,X)&col(A,B,Y))=>(perp(C,D,X,Y)))).
fof(perp_sym,axiom,![A,B,C,D]:((perp(A,B,C,D))=>(perp(C,D,A,B)))).
fof(th_8_15_1,axiom,(![A,B,C,X]:((A!=B&col(A,B,X)&perp(A,B,C,X))=>perp_in(X,A,B,C,X)))).
fof(per_col,axiom,![A,B,C,D]:((B!=C&per(A,B,C)&col(B,C,D))=>(per(A,B,D)))).
fof(th_8_2,axiom,(![A,B,C]:(per(A,B,C)=>per(C,B,A)))).
fof(midpoint_bet,axiom,![A,B,C]:((is_midpoint(B,A,C))=>(bet(A,B,C)))).
fof(th_7_25,axiom,(![A,B,C]:((cong(C,A,C,B))=>(?[X]:is_midpoint(X,A,B))))).
fof(th_7_4_2,axiom,(![P,A,P1,P2]:((is_midpoint(A,P,P1)&is_midpoint(A,P,P2))=>P1=P2))).
fof(th_7_4_1,axiom,(![P,A]:(?[P1]:is_midpoint(A,P,P1)))).
fof(th_7_3_1,axiom,(![A,M]:(is_midpoint(M,A,A)=>M=A))).
fof(th_7_2,axiom,(![A,M,B]:(is_midpoint(M,A,B)=>is_midpoint(M,B,A)))).
fof(col_transitivity_1,axiom,![P,Q,A,B]:((P!=Q&col(P,Q,A)&col(P,Q,B))=>(col(P,A,B)))).
fof(col_trivial_3,axiom,![A,B]:((col(A,B,A)))).
fof(col_trivial_2,axiom,![A,B]:((col(A,B,B)))).
fof(th_4_12,axiom,(![A,B]:col(A,A,B))).
fof(th_4_11,axiom,(![A,B,C]:(col(A,B,C)=>(col(B,C,A)&col(C,A,B)&col(C,B,A)&col(B,A,C)&col(A,C,B))))).
fof(th_3_17,axiom,(![A,B,C,A1,B1,P]:((bet(A,B,C)&bet(A1,B1,C)&bet(A,P,A1))=>(?[Q]:(bet(P,Q,C)&bet(B,Q,B1)))))).
fof(th_3_2,axiom,(![A,B,C]:(bet(A,B,C)=>bet(C,B,A)))).
fof(th_2_4,axiom,(![A,B,C,D]:(cong(A,B,C,D)=>cong(B,A,C,D)))).
fof(th_2_3,axiom,(![A,B,C,D,E,F]:((cong(A,B,C,D)&cong(C,D,E,F))=>cong(A,B,E,F)))).
fof(th_2_2,axiom,(![A,B,C,D]:(cong(A,B,C,D)=>cong(C,D,A,B)))).
fof(goal, conjecture,![A,B,C]:((A!=B&ncol(A,B,C))=>(?[P,T]:((perp(A,B,P,A)&col(A,B,T)&bet(C,T,P)))))).
