fof(ax_9_1_1,axiom,(![P,Q,A,B]:((two_sides(A,B,P,Q))=>(?[T]:(P!=Q&npoint_on_line(A,P,Q)&npoint_on_line(B,P,Q)&point_on_line(T,P,Q)&bet(A,T,B)))))).
fof(ax_9_1_2,axiom,(![P,Q,A,B,T]:((P!=Q&npoint_on_line(A,P,Q)&npoint_on_line(B,P,Q)&point_on_line(T,P,Q)&bet(A,T,B))=>two_sides(A,B,P,Q)))).
fof(ax_8_11_2_1,axiom,(![A,B,C,D]:(perp(A,B,C,D)=>(?[X]:perp_in(X,A,B,C,D))))).
fof(ax_8_11_2_2,axiom,(![X,A,B,C,D]:(perp_in(X,A,B,C,D)=>perp(A,B,C,D)))).
fof(ax_8_11_1_1,axiom,(![X,A,B,C,D]:((perp_in(X,A,B,C,D)&A!=X&C!=X)=>(A!=B&C!=D&point_on_line(X,A,B)&point_on_line(X,C,D)&per(A,X,C))))).
fof(ax_8_11_1_2,axiom,(![X,A,B,C,D]:((perp_in(X,A,B,C,D)&A!=X&D!=X)=>(A!=B&C!=D&point_on_line(X,A,B)&point_on_line(X,C,D)&per(A,X,D))))).
fof(ax_8_11_1_3,axiom,(![X,A,B,C,D]:((perp_in(X,A,B,C,D)&B!=X&C!=X)=>(A!=B&C!=D&point_on_line(X,A,B)&point_on_line(X,C,D)&per(B,X,C))))).
fof(ax_8_11_1_4,axiom,(![X,A,B,C,D]:((perp_in(X,A,B,C,D)&B!=X&D!=X)=>(A!=B&C!=D&point_on_line(X,A,B)&point_on_line(X,C,D)&per(B,X,D))))).
fof(ax_8_11_1_5,axiom,(![X,A,B,C,D]:((A!=X&C!=X&A!=B&C!=D&point_on_line(X,A,B)&point_on_line(X,C,D)&per(A,X,C))=>perp_in(X,A,B,C,D)))).
fof(ax_8_11_1_6,axiom,(![X,A,B,C,D]:((A!=X&D!=X&A!=B&C!=D&point_on_line(X,A,B)&point_on_line(X,C,D)&per(A,X,D))=>perp_in(X,A,B,C,D)))).
fof(ax_8_11_1_7,axiom,(![X,A,B,C,D]:((B!=X&C!=X&A!=B&C!=D&point_on_line(X,A,B)&point_on_line(X,C,D)&per(B,X,C))=>perp_in(X,A,B,C,D)))).
fof(ax_8_11_1_8,axiom,(![X,A,B,C,D]:((B!=X&D!=X&A!=B&C!=D&point_on_line(X,A,B)&point_on_line(X,C,D)&per(B,X,D))=>perp_in(X,A,B,C,D)))).
fof(ax_8_1_1,axiom,(![A,B,C]:((per(A,B,C))=>(?[C1]:(cong(A,C,A,C1)&is_midpoint(B,C,C1)))))).
fof(ax_8_1_2,axiom,(![A,B,C,C1]:((cong(A,C,A,C1)&is_midpoint(B,C,C1))=>per(A,B,C)))).
fof(ax_7_1,axiom,(![A,M,B]:((is_midpoint(M,A,B))=>(bet(A,M,B)&cong(M,A,M,B))))).
fof(ax_7_2,axiom,(![A,M,B]:((bet(A,M,B)&cong(M,A,M,B))=>is_midpoint(M,A,B)))).
fof(ax_6_1_1,axiom,(![A,B,P]:((out(P,A,B))=>((A!=P&B!=P&bet(P,A,B))|(A!=P&B!=P&bet(P,B,A)))))).
fof(ax_6_1_2,axiom,(![A,B,P]:((A!=P&B!=P&bet(P,A,B))=>out(P,A,B)))).
fof(ax_6_1_3,axiom,(![A,B,P]:((A!=P&B!=P&bet(P,B,A))=>out(P,A,B)))).
fof(ax_5_4_1,axiom,(![A,B,C,D]:(le(A,B,C,D)=>(?[Y]:(bet(C,Y,D)&cong(A,B,C,Y)))))).
fof(ax_5_4_2,axiom,(![A,B,C,D,Y]:((bet(C,Y,D)&cong(A,B,C,Y))=>(le(A,B,C,D))))).
fof(ax_4_10_1,axiom,(![A,B,C]:((col(A,B,C))=>(bet(A,B,C)|bet(B,C,A)|bet(C,A,B))))).
fof(ax_4_10_2,axiom,(![A,B,C]:((bet(A,B,C))=>col(A,B,C)))).
fof(ax_4_10_3,axiom,(![A,B,C]:((bet(B,C,A))=>col(A,B,C)))).
fof(ax_4_10_4,axiom,(![A,B,C]:((bet(C,A,B))=>col(A,B,C)))).
