fof(out_out_two_sides1,axiom,![P,Q,A,C,M,U,V]:((two_sides(A,C,P,Q)&col(M,P,Q)&perp(P,Q,A,M)&perp(P,Q,C,M)&out(M,U,A)&out(M,V,C))=>(two_sides(U,V,P,Q)))))).
fof(col_preserves_two_sides,axiom,![A,B,C,D,X,Y]:((A!=B&C!=D&col(A,B,C)&col(A,B,D)&two_sides(X,Y,A,B))=>(two_sides(X,Y,C,D))))).
fof(mid_two_sides,axiom,![A,B,M,X,Y]:((A!=B&is_midpoint(M,A,B)&ncol(A,B,X)&is_midpoint(M,X,Y))=>(two_sides(X,Y,A,B)))).
fof(th_9_4_1,axiom,(![P,Q,A,C,R,S,M,U,U1]:((two_sides(A,C,P,Q)&P!=Q&point_on_line(R,P,Q)&perp(P,Q,A,R)&point_on_line(S,P,Q)&perp(P,Q,C,S)&is_midpoint(M,R,S)&out(R,U,A)&is_symmetric(U,U1,M))=>out(S,U1,C)))).
fof(perp_col2,axiom,![A,B,C,D,X,Y]:((perp(A,B,X,Y)&C!=D&col(A,B,C)&col(A,B,D))=>(perp(C,D,X,Y)))).
fof(th_9_3,axiom,(![P,Q,A,B,C,M,R]:((two_sides(A,C,P,Q)&P!=Q&point_on_line(M,P,Q)&is_midpoint(M,A,C)&point_on_line(R,P,Q)&out(R,A,B))=>two_sides(B,C,P,Q)))).
fof(col2,axiom,![A,B,X,Y]:((A!=B&col(A,B,X)&col(A,B,Y))=>(col(A,X,Y)))).
fof(th_9_2,axiom,(![P,Q,A,B]:((two_sides(A,B,P,Q))=>two_sides(B,A,P,Q)))).
fof(th_8_24,axiom,(![A,B,P,Q,T,R]:((perp(P,A,A,B)&perp(Q,B,A,B)&col(A,B,T)&bet(P,T,Q)&bet(B,R,Q)&cong(A,P,B,R))=>(?[X]:(is_midpoint(X,A,B)&is_midpoint(X,P,R)))))).
fof(perp_left_comm,axiom,![A,B,C,D]:((perp(A,B,C,D))=>(perp(B,A,C,D)))).
fof(perp_sym,axiom,![A,B,C,D]:((perp(A,B,C,D))=>(perp(C,D,A,B)))).
fof(perp_distinct,axiom,![A,B,C,D]:((perp(A,B,C,D))=>((A!=B)&(C!=D)))).
fof(midpoint_bet,axiom,![A,B,C]:((is_midpoint(B,A,C))=>(bet(A,B,C)))).
fof(th_7_4_1,axiom,(![P,A]:(?[P1]:is_midpoint(A,P,P1)))).
fof(th_7_2,axiom,(![A,M,B]:(is_midpoint(M,A,B)=>is_midpoint(M,B,A)))).
fof(col_transitivity_1,axiom,![P,Q,A,B]:((P!=Q&col(P,Q,A)&col(P,Q,B))=>(col(P,A,B)))).
fof(th_6_7,axiom,(![A,B,C,P]:((out(P,A,B)&out(P,B,C))=>out(P,A,C)))).
fof(th_6_6,axiom,(![A,B,P]:(out(P,A,B)=>out(P,B,A)))).
fof(col_trivial_3,axiom,![A,B]:((col(A,B,A)))).
fof(th_4_12,axiom,(![A,B]:col(A,A,B))).
fof(th_4_11,axiom,(![A,B,C]:(col(A,B,C)=>(col(B,C,A)&col(C,A,B)&col(C,B,A)&col(B,A,C)&col(A,C,B))))).
fof(th_3_2,axiom,(![A,B,C]:(bet(A,B,C)=>bet(C,B,A)))).
fof(goal, conjecture,![P,Q,A,C,R,S,U,V]:((le(S,C,R,A)&two_sides(A,C,P,Q)&col(R,P,Q)&perp(P,Q,A,R)&col(S,P,Q)&perp(P,Q,C,S)&out(R,U,A)&out(S,V,C))=>(two_sides(U,V,P,Q)))).
