fof(ax_11_27_3,axiom,(![A,B,C,D,E,F]:(ge_angle(A,B,C,D,E,F)=>le_angle(D,E,F,A,B,C)))).
fof(ax_11_27_4,axiom,(![A,B,C,D,E,F]:(le_angle(D,E,F,A,B,C)=>ge_angle(A,B,C,D,E,F)))).
fof(ax_11_38_3,axiom,(![A,B,C,D,E,F]:(gt_angle(A,B,C,D,E,F)=>lt_angle(D,E,F,A,B,C)))).
fof(ax_11_38_4,axiom,(![A,B,C,D,E,F]:(lt_angle(A,B,C,D,E,F)=>gt_angle(D,E,F,A,B,C)))).
fof(ax_11_38_1,axiom,(![A,B,C,D,E,F]:((lt_angle(A,B,C,D,E,F))=>(le_angle(A,B,C,D,E,F)&ncong_angle(A,B,C,D,E,F))))).
fof(ax_11_38_2,axiom,(![A,B,C,D,E,F]:((le_angle(A,B,C,D,E,F)&ncong_angle(A,B,C,D,E,F))=>(lt_angle(A,B,C,D,E,F))))).
fof(ax_11_27_1,axiom,(![A,B,C,D,E,F]:((le_angle(A,B,C,D,E,F))=>(?[P]:(point_in_angle(P,D,E,F)&cong_angle(A,B,C,D,E,P)))))).
fof(ax_11_27_2,axiom,(![A,B,C,D,E,F,P]:((point_in_angle(P,D,E,F)&cong_angle(A,B,C,D,E,P))=>(le_angle(A,B,C,D,E,F))))).
fof(ax_11_23_1_1,axiom,(![A,B,C,P]:((point_in_angle(P,A,B,C))=>((?[X]:(A!=B&C!=B&P!=B&bet(A,X,C)&X=B))|(?[X]:(A!=B&C!=B&P!=B&bet(A,X,C)&out(B,X,P))))))).
fof(ax_11_23_1_2,axiom,(![A,B,C,P]:((A!=B&C!=B&P!=B&bet(A,B,C))=>(point_in_angle(P,A,B,C))))).
fof(ax_11_23_2,axiom,(![A,B,C,P,X]:((A!=B&C!=B&P!=B&bet(A,X,C)&out(B,X,P))=>point_in_angle(P,A,B,C)))).
fof(ax_11_2_1,axiom,(![A,B,C,D,E,F]:(cong_angle(A,B,C,D,E,F)=>(?[A1,C1,D1,F1]:(A!=B&C!=B&D!=E&F!=E&bet(B,A,A1)&cong(A,A1,E,D)&bet(B,C,C1)&cong(C,C1,E,F)&bet(E,D,D1)&cong(D,D1,B,A)&bet(E,F,F1)&cong(F,F1,B,C)&cong(A1,C1,D1,F1)))))).
fof(ax_11_2_2,axiom,(![A,B,C,D,E,F,A1,C1,D1,F1]:((A!=B&C!=B&D!=E&F!=E&bet(B,A,A1)&cong(A,A1,E,D)&bet(B,C,C1)&cong(C,C1,E,F)&bet(E,D,D1)&cong(D,D1,B,A)&bet(E,F,F1)&cong(F,F1,B,C)&cong(A1,C1,D1,F1))=>(cong_angle(A,B,C,D,E,F))))).
fof(ax_4_10_1,axiom,(![A,B,C]:((col(A,B,C))=>(bet(A,B,C)|bet(B,C,A)|bet(C,A,B))))).
fof(ax_4_10_2,axiom,(![A,B,C]:((bet(A,B,C))=>col(A,B,C)))).
fof(ax_4_10_3,axiom,(![A,B,C]:((bet(B,C,A))=>col(A,B,C)))).
fof(ax_4_10_4,axiom,(![A,B,C]:((bet(C,A,B))=>col(A,B,C)))).
