fof(not_par_other_side,axiom,![A,B,C,D,P]:((A!=B&C!=D&npar(A,B,C,D)&ncol(A,B,P))=>(?[Q]:((col(C,D,Q)&two_sides(A,B,P,Q)))))).
fof(line_dec,axiom,![B1,B2,C1,C2]:((col(C1,B1,B2)&col(C2,B1,B2))|ncol(C1,B1,B2)|ncol(C2,B1,B2))).
fof(par_strict_col2_par_strict,axiom,![A,B,C,D,E,F]:((E!=F&par_strict(A,B,C,D)&col(C,D,E)&col(C,D,F))=>(par_strict(A,B,E,F)))).
fof(par_col2_par,axiom,![A,B,C,D,E,F]:((E!=F&par(A,B,C,D)&col(C,D,E)&col(C,D,F))=>(par(A,B,E,F)))).
fof(par_not_col_strict,axiom,![A,B,C,D,P]:((par(A,B,C,D)&col(C,D,P)&ncol(A,B,P))=>(par_strict(A,B,C,D)))).
fof(par_distincts,axiom,![A,B,C,D]:((par(A,B,C,D))=>(par(A,B,C,D)&(A!=B)&(C!=D)))).
fof(col_not_col_not_par,axiom,![A,B,C,D,P,Q]:((col(A,B,P)&col(C,D,P)&(col(C,D,Q)&ncol(A,B,Q))=>(npar(A,B,C,D))))).
fof(par_not_col,axiom,![A,B,C,D,X]:((par_strict(A,B,C,D)&col(X,A,B))=>(ncol(X,C,D)))).
fof(th_12_6,axiom,(![A,B,C,D,P,P1]:((parallel(A,B,C,D)&point_on_line(P,C,D)&point_on_line(P1,C,D))=>one_side(P,P1,A,B)))).
fof(th_9_13,axiom,(![P,Q,A,B,C]:((one_side(A,B,P,Q)&one_side(B,C,P,Q))=>one_side(A,C,P,Q)))).
fof(th_9_9,axiom,(![P,Q,A,B]:(two_sides(A,B,P,Q)=>none_side(A,B,P,Q)))).
fof(th_7_4_1,axiom,(![P,A]:(?[P1]:is_midpoint(A,P,P1)))).
fof(th_6_23_2,axiom,(![A,B,C,P,Q]:((P!=Q&point_on_line(A,P,Q)&point_on_line(B,P,Q)&point_on_line(C,P,Q))=>col(A,B,C)))).
fof(col_transitivity_1,axiom,![P,Q,A,B]:((P!=Q&col(P,Q,A)&col(P,Q,B))=>(col(P,A,B)))).
fof(col_trivial_3,axiom,![A,B]:((col(A,B,A)))).
fof(col_trivial_2,axiom,![A,B]:((col(A,B,B)))).
fof(th_4_12,axiom,(![A,B]:col(A,A,B))).
fof(th_4_11,axiom,(![A,B,C]:(col(A,B,C)=>(col(B,C,A)&col(C,A,B)&col(C,B,A)&col(B,A,C)&col(A,C,B))))).
fof(th_3_2,axiom,(![A,B,C]:(bet(A,B,C)=>bet(C,B,A)))).
fof(goal, conjecture,![A1,A2,B1,B2,C1,C2,P]:((ncol(P,A1,A2)&par(A1,A2,B1,B2)&col(P,B1,B2)&par(A1,A2,C1,C2)&col(P,C1,C2))=>(col(C1,B1,B2)&col(C2,B1,B2))))).
