fof(ax_11_38_3,axiom,(![A,B,C,D,E,F]:(gt_angle(A,B,C,D,E,F)=>lt_angle(D,E,F,A,B,C)))).
fof(ax_11_38_4,axiom,(![A,B,C,D,E,F]:(lt_angle(A,B,C,D,E,F)=>gt_angle(D,E,F,A,B,C)))).
fof(ax_11_38_1,axiom,(![A,B,C,D,E,F]:((lt_angle(A,B,C,D,E,F))=>(le_angle(A,B,C,D,E,F)&ncong_angle(A,B,C,D,E,F))))).
fof(ax_11_38_2,axiom,(![A,B,C,D,E,F]:((le_angle(A,B,C,D,E,F)&ncong_angle(A,B,C,D,E,F))=>(lt_angle(A,B,C,D,E,F))))).
fof(ax_11_2_1,axiom,(![A,B,C,D,E,F]:(cong_angle(A,B,C,D,E,F)=>(?[A1,C1,D1,F1]:(A!=B&C!=B&D!=E&F!=E&bet(B,A,A1)&cong(A,A1,E,D)&bet(B,C,C1)&cong(C,C1,E,F)&bet(E,D,D1)&cong(D,D1,B,A)&bet(E,F,F1)&cong(F,F1,B,C)&cong(A1,C1,D1,F1)))))).
fof(ax_11_2_2,axiom,(![A,B,C,D,E,F,A1,C1,D1,F1]:((A!=B&C!=B&D!=E&F!=E&bet(B,A,A1)&cong(A,A1,E,D)&bet(B,C,C1)&cong(C,C1,E,F)&bet(E,D,D1)&cong(D,D1,B,A)&bet(E,F,F1)&cong(F,F1,B,C)&cong(A1,C1,D1,F1))=>(cong_angle(A,B,C,D,E,F))))).
fof(ax_5_14_3,axiom,![A,B,C,D]:(gt(C,D,A,B)=>lt(A,B,C,D))).
fof(ax_5_14_4,axiom,(![A,B,C,D]:(lt(A,B,C,D)=>gt(C,D,A,B)))).
fof(ax_5_14_1,axiom,![A,B,C,D]:((lt(A,B,C,D))=>(le(A,B,C,D)&ncong(A,B,C,D)))).
fof(ax_5_14_2,axiom,![A,B,C,D]:((le(A,B,C,D)&ncong(A,B,C,D))=>lt(A,B,C,D))).
fof(ax_4_10_1,axiom,(![A,B,C]:((col(A,B,C))=>(bet(A,B,C)|bet(B,C,A)|bet(C,A,B))))).
fof(ax_4_10_2,axiom,(![A,B,C]:((bet(A,B,C))=>col(A,B,C)))).
fof(ax_4_10_3,axiom,(![A,B,C]:((bet(B,C,A))=>col(A,B,C)))).
fof(ax_4_10_4,axiom,(![A,B,C]:((bet(C,A,B))=>col(A,B,C)))).
