fof(th_12_20,axiom,(![A,B,C,D]:((parallel_broad(A,B,C,D)&cong(A,B,C,D)&two_sides(B,D,A,C))=>(parallel_broad(B,C,D,A)&cong(B,C,D,A)&two_sides(A,C,B,D))))).
fof(th_12_19,axiom,(![A,B,C,D]:((ncol(A,B,C)&parallel_broad(A,B,C,D)&parallel_broad(B,C,D,A))=>(cong(A,B,C,D)&cong(B,C,D,A)&two_sides(B,D,A,C)&two_sides(A,C,B,D))))).
fof(th_12_16,axiom,(![A,B,C,D,P,Q,X]:((parallel_broad(A,B,C,D)&cop_lines3l(A,B,C,D,P,Q)&inter(X,P,Q,A,B))=>(?[Y]:inter(Y,P,Q,C,D))))).
fof(par_two_sides_two_sides,axiom,![A,B,C,D]:((par(A,B,C,D)&two_sides(A,C,B,D))=>(two_sides(B,D,A,C)))).
fof(inter_right_comm,axiom,![A,B,C,D,X]:((inter(A,B,C,D,X))=>(inter(A,B,D,C,X)))).
fof(inter_trivial,axiom,![A,B,X]:((ncol(A,B,X))=>(inter(A,X,B,X,X)))).
fof(par_col2_par,axiom,![A,B,C,D,E,F]:((E!=F&par(A,B,C,D)&col(C,D,E)&col(C,D,F))=>(par(A,B,E,F)))).
fof(par_not_col,axiom,![A,B,C,D,X]:((par_strict(A,B,C,D)&col(X,A,B))=>(ncol(X,C,D)))).
fof(par_col_par,axiom,![A,B,C,D,D1]:((C!=D1&par(A,B,C,D)&col(C,D,D1))=>(par(A,B,C,D1)))).
fof(th_12_10,axiom,(![A,B,P]:((A!=B)=>(?[C,D]:(C!=D&parallel_broad(A,B,C,D)&point_on_line(P,C,D)))))).
fof(th_12_6,axiom,(![A,B,C,D,P,P1]:((parallel(A,B,C,D)&point_on_line(P,C,D)&point_on_line(P1,C,D))=>one_side(P,P1,A,B)))).
fof(par_comm,axiom,![A,B,C,D]:((par(A,B,C,D))=>(par(B,A,D,C)))).
fof(par_right_comm,axiom,![A,B,C,D]:((par(A,B,C,D))=>(par(A,B,D,C)))).
fof(par_left_comm,axiom,![A,B,C,D]:((par(A,B,C,D))=>(par(B,A,C,D)))).
fof(par_symmetry,axiom,![A,B,C,D]:((par(A,B,C,D))=>(par(C,D,A,B)))).
fof(par_id,axiom,![A,B,C]:((par(A,B,A,C))=>(col(A,B,C)))).
fof(th_12_5_1,axiom,(![A,B,C,D]:((parallel(A,B,C,D))=>parallel(C,D,A,B)))).
fof(not_par_strict_id,axiom,![A,B,C]:((npar_strict(A,B,A,C)))).
fof(invert_one_side,axiom,![A,B,P,Q]:((one_side(P,Q,A,B))=>(one_side(P,Q,B,A)))).
fof(invert_two_sides,axiom,![A,B,P,Q]:((two_sides(P,Q,A,B))=>(two_sides(P,Q,B,A)))).
fof(col_one_side,axiom,![A,B,C,P,Q]:((col(A,B,C)&A!=C&one_side(P,Q,A,B))=>(one_side(P,Q,A,C)))).
fof(conga_comm,axiom,![A,B,C,D,E,F]:((cong_angle(A,B,C,D,E,F))=>(cong_angle(C,B,A,F,E,D)))).
fof(th_11_13,axiom,(![A,B,C,D,E,F,A1,D1]:((cong_angle(A,B,C,D,E,F)&bet(A,B,A1)&A1!=B&bet(D,E,D1)&D1!=E)=>cong_angle(A1,B,C,D1,E,F)))).
fof(th_11_10,axiom,(![A,B,C,D,E,F,A1,C1,D1,F1]:((cong_angle(A,B,C,D,E,F)&out(B,A1,A)&out(B,C1,C)&out(E,D1,D)&out(E,F1,F))=>cong_angle(A1,B,C1,D1,E,F1)))).
fof(th_11_8,axiom,(![A1,B1,C1,A2,B2,C2,A3,B3,C3]:((cong_angle(A1,B1,C1,A2,B2,C2)&cong_angle(A2,B2,C2,A3,B3,C3))=>cong_angle(A1,B1,C1,A3,B3,C3)))).
fof(cong3_conga,axiom,![A,B,C,A1,B1,C1]:((A!=B&C!=B&cong3(A,B,C,A1,B1,C1))=>(cong_angle(A,B,C,A1,B1,C1)))).
fof(bet_out,axiom,![A,B,C]:((B!=A&C!=A&bet(A,B,C))=>(out(A,B,C)))).
fof(th_11_7,axiom,(![A,B,C,D,E,F]:((cong_angle(A,B,C,D,E,F))=>cong_angle(D,E,F,A,B,C)))).
fof(th_11_6,axiom,(![A,B,C]:((A!=B&C!=B)=>cong_angle(A,B,C,A,B,C)))).
fof(th_9_13,axiom,(![P,Q,A,B,C]:((one_side(A,B,P,Q)&one_side(B,C,P,Q))=>one_side(A,C,P,Q)))).
fof(th_9_12,axiom,(![P,Q,A,B]:((one_side(A,B,P,Q))=>one_side(B,A,P,Q)))).
fof(th_9_9,axiom,(![P,Q,A,B]:(two_sides(A,B,P,Q)=>none_side(A,B,P,Q)))).
fof(th_9_8_2,axiom,(![P,Q,A,B,C]:((two_sides(A,C,P,Q)&one_side(A,B,P,Q))=>two_sides(B,C,P,Q)))).
fof(th_9_2,axiom,(![P,Q,A,B]:((two_sides(A,B,P,Q))=>two_sides(B,A,P,Q)))).
fof(col_transitivity_1,axiom,![P,Q,A,B]:((P!=Q&col(P,Q,A)&col(P,Q,B))=>(col(P,A,B)))).
fof(th_6_6,axiom,(![A,B,P]:(out(P,A,B)=>out(P,B,A)))).
fof(th_6_5,axiom,(![A,P]:(A!=P=>out(P,A,A)))).
fof(out_col,axiom,![A,B,C]:((out(A,B,C))=>(col(A,B,C)))).
fof(th_5_2,axiom,(![A,B,C,D]:((A!=B&bet(A,B,C)&bet(A,B,D))=>(bet(B,C,D)|bet(B,D,C))))).
fof(th_5_1,axiom,(![A,B,C,D]:((A!=B&bet(A,B,C)&bet(A,B,D))=>(bet(A,C,D)|bet(A,D,C))))).
fof(col_trivial_3,axiom,![A,B]:((col(A,B,A)))).
fof(col_trivial_2,axiom,![A,B]:((col(A,B,B)))).
fof(th_4_12,axiom,(![A,B]:col(A,A,B))).
fof(th_4_11,axiom,(![A,B,C]:(col(A,B,C)=>(col(B,C,A)&col(C,A,B)&col(C,B,A)&col(B,A,C)&col(A,C,B))))).
fof(th_3_6,axiom,(![A,B,C,D]:((bet(A,B,C)&bet(A,C,D))=>(bet(B,C,D)&bet(A,B,D))))).
fof(th_3_7,axiom,(![A,B,C,D]:((bet(A,B,C)&bet(B,C,D)&B!=C)=>(bet(A,C,D)&bet(A,B,D))))).
fof(th_3_2,axiom,(![A,B,C]:(bet(A,B,C)=>bet(C,B,A)))).
fof(cong_commutativity,axiom,![A,B,C,D]:((cong(A,B,C,D))=>(cong(B,A,D,C)))).
fof(th_2_5,axiom,(![A,B,C,D]:(cong(A,B,C,D)=>cong(A,B,D,C)))).
fof(th_2_4,axiom,(![A,B,C,D]:(cong(A,B,C,D)=>cong(B,A,C,D)))).
fof(th_2_3,axiom,(![A,B,C,D,E,F]:((cong(A,B,C,D)&cong(C,D,E,F))=>cong(A,B,E,F)))).
fof(th_2_2,axiom,(![A,B,C,D]:(cong(A,B,C,D)=>cong(C,D,A,B)))).
fof(goal, conjecture,(![A,B,C,D,P]:((out(P,A,C)&one_side(B,D,P,A)&parallel_broad(A,B,C,D))=>cong_angle(B,A,P,D,C,P)))).
