fof(th_10_15,axiom,(![A,B,A1,Q]:((A!=B&point_on_line(A1,A,B)&npoint_on_line(Q,A,B))=>(?[P]:(perp(A,B,P,A1)&one_side(P,Q,A,B)))))).
fof(th_10_12,axiom,(![A,B,C,A1,B1,C1]:((per(A,B,C)&per(A1,B1,C1)&cong(A,B,A1,B1)&cong(B,C,B1,C1))=>cong(A,C,A1,C1)))).
fof(th_9_19_1,axiom,(![P,Q,P1,A,B]:((P!=Q&point_on_line(P1,P,Q)&col(A,B,P1)&one_side(A,B,P,Q))=>(out(P1,A,B)&npoint_on_line(A,P,Q))))).
fof(th_9_13,axiom,(![P,Q,A,B,C]:((one_side(A,B,P,Q)&one_side(B,C,P,Q))=>one_side(A,C,P,Q)))).
fof(th_9_12,axiom,(![P,Q,A,B]:((one_side(A,B,P,Q))=>one_side(B,A,P,Q)))).
fof(perp_col,axiom,![A,B,C,D,E]:((A!=E&perp(A,B,C,D)&col(A,B,E))=>(perp(A,E,C,D)))).
fof(th_8_18_1,axiom,(![A,B,C]:(ncol(A,B,C)=>(?[X]:(col(A,B,X)&perp(A,B,C,X)))))).
fof(perp_comm,axiom,![A,B,C,D]:((perp(A,B,C,D))=>(perp(B,A,D,C)))).
fof(perp_right_comm,axiom,![A,B,C,D]:((perp(A,B,C,D))=>(perp(A,B,D,C)))).
fof(perp_sym,axiom,![A,B,C,D]:((perp(A,B,C,D))=>(perp(C,D,A,B)))).
fof(perp_in_per,axiom,![A,B,C]:((perp_in(B,A,B,B,C))=>(per(A,B,C)))).
fof(th_8_14_2_2,axiom,(![X,A,B,C,D]:((perp(A,B,C,D)&inter(X,A,B,C,D))=>perp_in(X,A,B,C,D)))).
fof(perp_distinct,axiom,![A,B,C,D]:((perp(A,B,C,D))=>((A!=B)&(C!=D)))).
fof(th_6_11_1,axiom,(![R,A,B,C]:((R!=A&B!=C)=>(?[X]:(out(A,X,R)&cong(A,X,B,C)))))).
fof(out_col,axiom,![A,B,C]:((out(A,B,C))=>(col(A,B,C)))).
fof(th_4_14,axiom,(![A,B,C,A1,B1]:((col(A,B,C)&cong(A,B,A1,B1))=>(?[C1]:(cong3(A,B,C,A1,B1,C1)))))).
fof(th_4_13,axiom,(![A,B,C,A1,B1,C1]:((col(A,B,C)&cong3(A,B,C,A1,B1,C1))=>col(A1,B1,C1)))).
fof(col_trivial_3,axiom,![A,B]:((col(A,B,A)))).
fof(th_4_12,axiom,(![A,B]:col(A,A,B))).
fof(th_4_11,axiom,(![A,B,C]:(col(A,B,C)=>(col(B,C,A)&col(C,A,B)&col(C,B,A)&col(B,A,C)&col(A,C,B))))).
fof(th_2_2,axiom,(![A,B,C,D]:(cong(A,B,C,D)=>cong(C,D,A,B)))).
fof(goal, conjecture,(![A,B,C,A1,B1,P]:((ncol(A,B,C)&ncol(A1,B1,P)&cong(A,B,A1,B1))=>(?[C1]:((cong3(A,B,C,A1,B1,C1)&one_side(C1,P,A1,B1))))))).
