fof(image_col,axiom,![A,B,X]:((A!=B&col(A,B,X))=>(is_image_spec(X,X,A,B)))).
fof(per_perp,axiom,![A,B,C,D]:((A!=B&B!=C&D!=B&D!=C&col(B,C,D)&per(A,B,C))=>(perp(C,D,A,B)))).
fof(image_preserves_per,axiom,![A,B,C,A1,B1,C1,X,Y]:((X!=Y&is_image_spec(A,A1,X,Y)&is_image_spec(B,B1,X,Y)&is_image_spec(C,C1,X,Y)&per(A,B,C))=>(per(A1,B1,C1)))).
fof(l10_10_spec,axiom,![A,B,P,Q,P1,Q1]:((A!=B&is_image_spec(P1,P,A,B)&is_image_spec(Q1,Q,A,B))=>(cong(P,Q,P1,Q1)))).
fof(is_image_spec_col_cong,axiom,![A,B,P,P1,X]:((A!=B&is_image_spec(P,P1,A,B)&col(A,B,X))=>(cong(P,X,P1,X)))).
fof(l10_6_existence_spec,axiom,![A,B,P1]:((A!=B)=>(?[P]:((is_image_spec(P1,P,A,B)))))).
fof(l10_4_spec,axiom,![A,B,P,P1]:((A!=B&is_image_spec(P,P1,A,B))=>(is_image_spec(P1,P,A,B)))).
fof(th_8_22_1,axiom,(![A,B]:(?[X]:is_midpoint(X,A,B)))).
fof(per_per_col,axiom,![A,B,C,X]:((per(A,X,C)&X!=C&per(B,X,C))=>(col(A,B,X)))).
fof(is_midpoint_id,axiom,![A,B]:((is_midpoint(A,A,B))=>(A=B))).
fof(perp_sym,axiom,![A,B,C,D]:((perp(A,B,C,D))=>(perp(C,D,A,B)))).
fof(th_8_10,axiom,(![A,B,C,A1,B1,C1]:((per(A,B,C)&cong3(A,B,C,A1,B1,C1))=>per(A1,B1,C1)))).
fof(th_8_3,axiom,(![A,B,C,A1]:((per(A,B,C)&A!=B&col(B,A,A1))=>per(A1,B,C)))).
fof(th_8_2,axiom,(![A,B,C]:(per(A,B,C)=>per(C,B,A)))).
fof(midpoint_col,axiom,![A,M,B]:((is_midpoint(M,A,B))=>(col(M,A,B)))).
fof(midpoint_distinct_1,axiom,![I,A,B]:((A!=B&is_midpoint(I,A,B))=>((I!=A)&(I!=B)))).
fof(th_7_20,axiom,(![A,M,B]:((col(A,M,B)&cong(M,A,M,B))=>(A=B|is_midpoint(M,A,B))))).
fof(th_7_13,axiom,(![P,Q,A,P1,Q1]:((is_symmetric(P,P1,A)&is_symmetric(Q,Q1,A))=>cong(P,Q,P1,Q1)))).
fof(th_7_8_2,axiom,(![P1,A,P,Q]:((is_symmetric(P,P1,A)&is_symmetric(Q,P1,A))=>P=Q))).
fof(th_7_4_2,axiom,(![P,A,P1,P2]:((is_midpoint(A,P,P1)&is_midpoint(A,P,P2))=>P1=P2))).
fof(th_7_4_1,axiom,(![P,A]:(?[P1]:is_midpoint(A,P,P1)))).
fof(th_7_2,axiom,(![A,M,B]:(is_midpoint(M,A,B)=>is_midpoint(M,B,A)))).
fof(col_trivial_3,axiom,![A,B]:((col(A,B,A)))).
fof(col_trivial_2,axiom,![A,B]:((col(A,B,B)))).
fof(th_4_11,axiom,(![A,B,C]:(col(A,B,C)=>(col(B,C,A)&col(C,A,B)&col(C,B,A)&col(B,A,C)&col(A,C,B))))).
fof(cong_commutativity,axiom,![A,B,C,D]:((cong(A,B,C,D))=>(cong(B,A,D,C)))).
fof(th_2_3,axiom,(![A,B,C,D,E,F]:((cong(A,B,C,D)&cong(C,D,E,F))=>cong(A,B,E,F)))).
fof(th_2_2,axiom,(![A,B,C,D]:(cong(A,B,C,D)=>cong(C,D,A,B)))).
fof(goal, conjecture,(![A,B,C,A1,B1,C1]:((per(A,B,C)&per(A1,B1,C1)&cong(A,B,A1,B1)&cong(B,C,B1,C1))=>cong(A,C,A1,C1)))).
