fof(deftriangle,axiom, (! [A,B,C] : ((triangle(A,B,C)) => ((ncol(A,B,C)))))).
fof(deftriangle2,axiom, (! [A,B,C] : ((ncol(A,B,C)) => ((triangle(A,B,C)))))).
fof(lemma_NCdistinct,axiom, (! [A,B,C] : ((ncol(A,B,C)) => ((neq(A,B) & neq(B,C) & neq(A,C) & neq(B,A) & neq(C,B) & neq(C,A)))))).
fof(lemma_extension,axiom, (! [A,B,P,Q] : (? [X] : ((neq(A,B) & neq(P,Q)) => ((betS(A,B,X) & cong(B,X,P,Q))))))).
fof(lemma_NCorder,axiom, (! [A,B,C] : ((ncol(A,B,C)) => ((ncol(B,A,C) & ncol(B,C,A) & ncol(C,A,B) & ncol(A,C,B) & ncol(C,B,A)))))).
fof(defcollinear,axiom, (! [A,B,C] : ((col(A,B,C)) => ((eq(A,B)) | (eq(A,C)) | (eq(B,C)) | (betS(B,A,C)) | (betS(A,B,C)) | (betS(A,C,B)))))).
fof(defcollinear2a,axiom, (! [A,B,C] : ((eq(A,B)) => ((col(A,B,C)))))).
fof(defcollinear2b,axiom, (! [A,B,C] : ((eq(A,C)) => ((col(A,B,C)))))).
fof(defcollinear2c,axiom, (! [A,B,C] : ((eq(B,C)) => ((col(A,B,C)))))).
fof(defcollinear2d,axiom, (! [A,B,C] : ((betS(B,A,C)) => ((col(A,B,C)))))).
fof(defcollinear2e,axiom, (! [A,B,C] : ((betS(A,B,C)) => ((col(A,B,C)))))).
fof(defcollinear2f,axiom, (! [A,B,C] : ((betS(A,C,B)) => ((col(A,B,C)))))).
fof(lemma_betweennotequal,axiom, (! [A,B,C] : ((betS(A,B,C)) => ((neq(B,C) & neq(A,B) & neq(A,C)))))).
fof(lemma_NChelper,axiom, (! [A,B,C,P,Q] : ((ncol(A,B,C) & col(A,B,P) & col(A,B,Q) & neq(P,Q)) => ((ncol(P,Q,C)))))).
fof(proposition_16,axiom, (! [A,B,C,D] : ((triangle(A,B,C) & betS(B,C,D)) => ((ltA(B,A,C,A,C,D) & ltA(C,B,A,A,C,D)))))).
fof(lemma_ABCequalsCBA,axiom, (! [A,B,C] : ((ncol(A,B,C)) => ((congA(A,B,C,C,B,A)))))).
fof(lemma_angleorderrespectscongruence2,axiom, (! [A,B,C,D,E,F,Xa,Xb,Xc] : ((ltA(A,B,C,D,E,F) & congA(Xa,Xb,Xc,A,B,C)) => ((ltA(Xa,Xb,Xc,D,E,F)))))).
fof(defanglelessthan,axiom, (! [A,B,C,D,E,F] : (? [U,X,V] : ((ltA(A,B,C,D,E,F)) => ((betS(U,X,V) & out(E,D,U) & out(E,F,V) & congA(A,B,C,D,E,X))))))).
fof(defanglelessthan2,axiom, (! [A,B,C,D,E,F,U,X,V] : ((betS(U,X,V) & out(E,D,U) & out(E,F,V) & congA(A,B,C,D,E,X)) => ((ltA(A,B,C,D,E,F)))))).
fof(lemma_ray5,axiom, (! [A,B,C] : ((out(A,B,C)) => ((out(A,C,B)))))).
fof(lemma_rayimpliescollinear,axiom, (! [A,B,C] : ((out(A,B,C)) => ((col(A,B,C)))))).
fof(lemma_ray2,axiom, (! [A,B,C] : ((out(A,B,C)) => ((neq(A,B)))))).
fof(lemma_crossbar,axiom, (! [A,B,C,E,U,V] : (? [X] : ((triangle(A,B,C) & betS(A,E,C) & out(B,A,U) & out(B,C,V)) => ((out(B,E,X) & betS(U,X,V))))))).
fof(lemma_collinearorder,axiom, (! [A,B,C] : ((col(A,B,C)) => ((col(B,A,C) & col(B,C,A) & col(C,A,B) & col(A,C,B) & col(C,B,A)))))).
fof(lemma_inequalitysymmetric,axiom, (! [A,B] : ((neq(A,B)) => ((neq(B,A)))))).
fof(lemma_equalanglesreflexive,axiom, (! [A,B,C] : ((ncol(A,B,C)) => ((congA(A,B,C,A,B,C)))))).
fof(lemma_equalangleshelper,axiom, (! [A,B,C,Xa,Xb,Xc,Xp,Xq] : ((congA(A,B,C,Xa,Xb,Xc) & out(Xb,Xa,Xp) & out(Xb,Xc,Xq)) => ((congA(A,B,C,Xp,Xb,Xq)))))).
fof(lemma_ray4_1,axiom, (! [A,B,E] : ((betS(A,E,B) & neq(A,B)) => ((out(A,B,E)))))).
fof(lemma_ray4_2,axiom, (! [A,B,E] : ((eq(E,B) & neq(A,B)) => ((out(A,B,E)))))).
fof(lemma_ray4_3,axiom, (! [A,B,E] : ((betS(A,B,E) & neq(A,B)) => ((out(A,B,E)))))).
fof(lemma_equalanglestransitive,axiom, (! [A,B,C,D,E,F,P,Q,R] : ((congA(A,B,C,D,E,F) & congA(D,E,F,P,Q,R)) => ((congA(A,B,C,P,Q,R)))))).
fof(postulate_Pasch_inner,axiom, (! [A,B,C,P,Q] : (? [X] : ((betS(A,P,C) & betS(B,Q,C) & ncol(A,C,B)) => ((betS(A,X,Q) & betS(B,X,P))))))).
fof(axiom_betweennesssymmetry,axiom, (! [A,B,C] : ((betS(A,B,C)) => ((betS(C,B,A)))))).
fof(defanglesum,axiom, (! [A,B,C,D,E,F,P,Q,R] : (? [X] : ((sumA(A,B,C,D,E,F,P,Q,R)) => ((congA(A,B,C,P,Q,X) & congA(D,E,F,X,Q,R) & betS(P,X,R))))))).
fof(defanglesum2,axiom, (! [A,B,C,D,E,F,P,Q,R,X] : ((congA(A,B,C,P,Q,X) & congA(D,E,F,X,Q,R) & betS(P,X,R)) => ((sumA(A,B,C,D,E,F,P,Q,R)))))).
fof(eqSymmetric,axiom, (! [A,B] : ((eq(A,B)) => ((eq(B,A)))))).
fof(neqSymmetric,axiom, (! [A,B] : ((neq(A,B)) => ((neq(B,A)))))).
fof(eqReflexive,axiom, (! [A] : ((eq(A,A))))).
fof(triangle_neg_elim,axiom, (! [A,B,C] : ((triangle(A,B,C) & ntriangle(A,B,C)) => (($false))))).
fof(col_neg_elim,axiom, (! [A,B,C] : ((col(A,B,C) & ncol(A,B,C)) => (($false))))).
fof(eq_neg_elim,axiom, (! [A,B] : ((eq(A,B) & neq(A,B)) => (($false))))).
fof(betS_neg_elim,axiom, (! [A,B,C] : ((betS(A,B,C) & nbetS(A,B,C)) => (($false))))).
fof(cong_neg_elim,axiom, (! [A,B,C,D] : ((cong(A,B,C,D) & ncong(A,B,C,D)) => (($false))))).
fof(ltA_neg_elim,axiom, (! [A,B,C,D,E,F] : ((ltA(A,B,C,D,E,F) & nltA(A,B,C,D,E,F)) => (($false))))).
fof(congA_neg_elim,axiom, (! [A,B,C,D,E,F] : ((congA(A,B,C,D,E,F) & ncongA(A,B,C,D,E,F)) => (($false))))).
fof(out_neg_elim,axiom, (! [A,B,C] : ((out(A,B,C) & nout(A,B,C)) => (($false))))).
fof(sumA_neg_elim,axiom, (! [A,B,C,D,E,F,G,H,I] : ((sumA(A,B,C,D,E,F,G,H,I) & nsumA(A,B,C,D,E,F,G,H,I)) => (($false))))).
fof(triangle_excluded_middle,axiom, (! [A,B,C] : ((triangle(A,B,C)) | (ntriangle(A,B,C))))).
fof(col_excluded_middle,axiom, (! [A,B,C] : ((col(A,B,C)) | (ncol(A,B,C))))).
fof(eq_excluded_middle,axiom, (! [A,B] : ((eq(A,B)) | (neq(A,B))))).
fof(betS_excluded_middle,axiom, (! [A,B,C] : ((betS(A,B,C)) | (nbetS(A,B,C))))).
fof(cong_excluded_middle,axiom, (! [A,B,C,D] : ((cong(A,B,C,D)) | (ncong(A,B,C,D))))).
fof(ltA_excluded_middle,axiom, (! [A,B,C,D,E,F] : ((ltA(A,B,C,D,E,F)) | (nltA(A,B,C,D,E,F))))).
fof(congA_excluded_middle,axiom, (! [A,B,C,D,E,F] : ((congA(A,B,C,D,E,F)) | (ncongA(A,B,C,D,E,F))))).
fof(out_excluded_middle,axiom, (! [A,B,C] : ((out(A,B,C)) | (nout(A,B,C))))).
fof(sumA_excluded_middle,axiom, (! [A,B,C,D,E,F,G,H,I] : ((sumA(A,B,C,D,E,F,G,H,I)) | (nsumA(A,B,C,D,E,F,G,H,I))))).
fof(triangle_EqSub_0,axiom, (! [A,B,C,X] : ((eq(A,X) & triangle(A,B,C)) => ((triangle(X,B,C)))))).
fof(triangle_EqSub_1,axiom, (! [A,B,C,X] : ((eq(B,X) & triangle(A,B,C)) => ((triangle(A,X,C)))))).
fof(triangle_EqSub_2,axiom, (! [A,B,C,X] : ((eq(C,X) & triangle(A,B,C)) => ((triangle(A,B,X)))))).
fof(ntriangle_EqSub_0,axiom, (! [A,B,C,X] : ((eq(A,X) & ntriangle(A,B,C)) => ((ntriangle(X,B,C)))))).
fof(ntriangle_EqSub_1,axiom, (! [A,B,C,X] : ((eq(B,X) & ntriangle(A,B,C)) => ((ntriangle(A,X,C)))))).
fof(ntriangle_EqSub_2,axiom, (! [A,B,C,X] : ((eq(C,X) & ntriangle(A,B,C)) => ((ntriangle(A,B,X)))))).
fof(col_EqSub_0,axiom, (! [A,B,C,X] : ((eq(A,X) & col(A,B,C)) => ((col(X,B,C)))))).
fof(col_EqSub_1,axiom, (! [A,B,C,X] : ((eq(B,X) & col(A,B,C)) => ((col(A,X,C)))))).
fof(col_EqSub_2,axiom, (! [A,B,C,X] : ((eq(C,X) & col(A,B,C)) => ((col(A,B,X)))))).
fof(ncol_EqSub_0,axiom, (! [A,B,C,X] : ((eq(A,X) & ncol(A,B,C)) => ((ncol(X,B,C)))))).
fof(ncol_EqSub_1,axiom, (! [A,B,C,X] : ((eq(B,X) & ncol(A,B,C)) => ((ncol(A,X,C)))))).
fof(ncol_EqSub_2,axiom, (! [A,B,C,X] : ((eq(C,X) & ncol(A,B,C)) => ((ncol(A,B,X)))))).
fof(eq_EqSub_0,axiom, (! [A,B,X] : ((eq(A,X) & eq(A,B)) => ((eq(X,B)))))).
fof(eq_EqSub_1,axiom, (! [A,B,X] : ((eq(B,X) & eq(A,B)) => ((eq(A,X)))))).
fof(neq_EqSub_0,axiom, (! [A,B,X] : ((eq(A,X) & neq(A,B)) => ((neq(X,B)))))).
fof(neq_EqSub_1,axiom, (! [A,B,X] : ((eq(B,X) & neq(A,B)) => ((neq(A,X)))))).
fof(betS_EqSub_0,axiom, (! [A,B,C,X] : ((eq(A,X) & betS(A,B,C)) => ((betS(X,B,C)))))).
fof(betS_EqSub_1,axiom, (! [A,B,C,X] : ((eq(B,X) & betS(A,B,C)) => ((betS(A,X,C)))))).
fof(betS_EqSub_2,axiom, (! [A,B,C,X] : ((eq(C,X) & betS(A,B,C)) => ((betS(A,B,X)))))).
fof(nbetS_EqSub_0,axiom, (! [A,B,C,X] : ((eq(A,X) & nbetS(A,B,C)) => ((nbetS(X,B,C)))))).
fof(nbetS_EqSub_1,axiom, (! [A,B,C,X] : ((eq(B,X) & nbetS(A,B,C)) => ((nbetS(A,X,C)))))).
fof(nbetS_EqSub_2,axiom, (! [A,B,C,X] : ((eq(C,X) & nbetS(A,B,C)) => ((nbetS(A,B,X)))))).
fof(cong_EqSub_0,axiom, (! [A,B,C,D,X] : ((eq(A,X) & cong(A,B,C,D)) => ((cong(X,B,C,D)))))).
fof(cong_EqSub_1,axiom, (! [A,B,C,D,X] : ((eq(B,X) & cong(A,B,C,D)) => ((cong(A,X,C,D)))))).
fof(cong_EqSub_2,axiom, (! [A,B,C,D,X] : ((eq(C,X) & cong(A,B,C,D)) => ((cong(A,B,X,D)))))).
fof(cong_EqSub_3,axiom, (! [A,B,C,D,X] : ((eq(D,X) & cong(A,B,C,D)) => ((cong(A,B,C,X)))))).
fof(ncong_EqSub_0,axiom, (! [A,B,C,D,X] : ((eq(A,X) & ncong(A,B,C,D)) => ((ncong(X,B,C,D)))))).
fof(ncong_EqSub_1,axiom, (! [A,B,C,D,X] : ((eq(B,X) & ncong(A,B,C,D)) => ((ncong(A,X,C,D)))))).
fof(ncong_EqSub_2,axiom, (! [A,B,C,D,X] : ((eq(C,X) & ncong(A,B,C,D)) => ((ncong(A,B,X,D)))))).
fof(ncong_EqSub_3,axiom, (! [A,B,C,D,X] : ((eq(D,X) & ncong(A,B,C,D)) => ((ncong(A,B,C,X)))))).
fof(ltA_EqSub_0,axiom, (! [A,B,C,D,E,F,X] : ((eq(A,X) & ltA(A,B,C,D,E,F)) => ((ltA(X,B,C,D,E,F)))))).
fof(ltA_EqSub_1,axiom, (! [A,B,C,D,E,F,X] : ((eq(B,X) & ltA(A,B,C,D,E,F)) => ((ltA(A,X,C,D,E,F)))))).
fof(ltA_EqSub_2,axiom, (! [A,B,C,D,E,F,X] : ((eq(C,X) & ltA(A,B,C,D,E,F)) => ((ltA(A,B,X,D,E,F)))))).
fof(ltA_EqSub_3,axiom, (! [A,B,C,D,E,F,X] : ((eq(D,X) & ltA(A,B,C,D,E,F)) => ((ltA(A,B,C,X,E,F)))))).
fof(ltA_EqSub_4,axiom, (! [A,B,C,D,E,F,X] : ((eq(E,X) & ltA(A,B,C,D,E,F)) => ((ltA(A,B,C,D,X,F)))))).
fof(ltA_EqSub_5,axiom, (! [A,B,C,D,E,F,X] : ((eq(F,X) & ltA(A,B,C,D,E,F)) => ((ltA(A,B,C,D,E,X)))))).
fof(nltA_EqSub_0,axiom, (! [A,B,C,D,E,F,X] : ((eq(A,X) & nltA(A,B,C,D,E,F)) => ((nltA(X,B,C,D,E,F)))))).
fof(nltA_EqSub_1,axiom, (! [A,B,C,D,E,F,X] : ((eq(B,X) & nltA(A,B,C,D,E,F)) => ((nltA(A,X,C,D,E,F)))))).
fof(nltA_EqSub_2,axiom, (! [A,B,C,D,E,F,X] : ((eq(C,X) & nltA(A,B,C,D,E,F)) => ((nltA(A,B,X,D,E,F)))))).
fof(nltA_EqSub_3,axiom, (! [A,B,C,D,E,F,X] : ((eq(D,X) & nltA(A,B,C,D,E,F)) => ((nltA(A,B,C,X,E,F)))))).
fof(nltA_EqSub_4,axiom, (! [A,B,C,D,E,F,X] : ((eq(E,X) & nltA(A,B,C,D,E,F)) => ((nltA(A,B,C,D,X,F)))))).
fof(nltA_EqSub_5,axiom, (! [A,B,C,D,E,F,X] : ((eq(F,X) & nltA(A,B,C,D,E,F)) => ((nltA(A,B,C,D,E,X)))))).
fof(congA_EqSub_0,axiom, (! [A,B,C,D,E,F,X] : ((eq(A,X) & congA(A,B,C,D,E,F)) => ((congA(X,B,C,D,E,F)))))).
fof(congA_EqSub_1,axiom, (! [A,B,C,D,E,F,X] : ((eq(B,X) & congA(A,B,C,D,E,F)) => ((congA(A,X,C,D,E,F)))))).
fof(congA_EqSub_2,axiom, (! [A,B,C,D,E,F,X] : ((eq(C,X) & congA(A,B,C,D,E,F)) => ((congA(A,B,X,D,E,F)))))).
fof(congA_EqSub_3,axiom, (! [A,B,C,D,E,F,X] : ((eq(D,X) & congA(A,B,C,D,E,F)) => ((congA(A,B,C,X,E,F)))))).
fof(congA_EqSub_4,axiom, (! [A,B,C,D,E,F,X] : ((eq(E,X) & congA(A,B,C,D,E,F)) => ((congA(A,B,C,D,X,F)))))).
fof(congA_EqSub_5,axiom, (! [A,B,C,D,E,F,X] : ((eq(F,X) & congA(A,B,C,D,E,F)) => ((congA(A,B,C,D,E,X)))))).
fof(ncongA_EqSub_0,axiom, (! [A,B,C,D,E,F,X] : ((eq(A,X) & ncongA(A,B,C,D,E,F)) => ((ncongA(X,B,C,D,E,F)))))).
fof(ncongA_EqSub_1,axiom, (! [A,B,C,D,E,F,X] : ((eq(B,X) & ncongA(A,B,C,D,E,F)) => ((ncongA(A,X,C,D,E,F)))))).
fof(ncongA_EqSub_2,axiom, (! [A,B,C,D,E,F,X] : ((eq(C,X) & ncongA(A,B,C,D,E,F)) => ((ncongA(A,B,X,D,E,F)))))).
fof(ncongA_EqSub_3,axiom, (! [A,B,C,D,E,F,X] : ((eq(D,X) & ncongA(A,B,C,D,E,F)) => ((ncongA(A,B,C,X,E,F)))))).
fof(ncongA_EqSub_4,axiom, (! [A,B,C,D,E,F,X] : ((eq(E,X) & ncongA(A,B,C,D,E,F)) => ((ncongA(A,B,C,D,X,F)))))).
fof(ncongA_EqSub_5,axiom, (! [A,B,C,D,E,F,X] : ((eq(F,X) & ncongA(A,B,C,D,E,F)) => ((ncongA(A,B,C,D,E,X)))))).
fof(out_EqSub_0,axiom, (! [A,B,C,X] : ((eq(A,X) & out(A,B,C)) => ((out(X,B,C)))))).
fof(out_EqSub_1,axiom, (! [A,B,C,X] : ((eq(B,X) & out(A,B,C)) => ((out(A,X,C)))))).
fof(out_EqSub_2,axiom, (! [A,B,C,X] : ((eq(C,X) & out(A,B,C)) => ((out(A,B,X)))))).
fof(nout_EqSub_0,axiom, (! [A,B,C,X] : ((eq(A,X) & nout(A,B,C)) => ((nout(X,B,C)))))).
fof(nout_EqSub_1,axiom, (! [A,B,C,X] : ((eq(B,X) & nout(A,B,C)) => ((nout(A,X,C)))))).
fof(nout_EqSub_2,axiom, (! [A,B,C,X] : ((eq(C,X) & nout(A,B,C)) => ((nout(A,B,X)))))).
fof(sumA_EqSub_0,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(A,X) & sumA(A,B,C,D,E,F,G,H,I)) => ((sumA(X,B,C,D,E,F,G,H,I)))))).
fof(sumA_EqSub_1,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(B,X) & sumA(A,B,C,D,E,F,G,H,I)) => ((sumA(A,X,C,D,E,F,G,H,I)))))).
fof(sumA_EqSub_2,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(C,X) & sumA(A,B,C,D,E,F,G,H,I)) => ((sumA(A,B,X,D,E,F,G,H,I)))))).
fof(sumA_EqSub_3,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(D,X) & sumA(A,B,C,D,E,F,G,H,I)) => ((sumA(A,B,C,X,E,F,G,H,I)))))).
fof(sumA_EqSub_4,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(E,X) & sumA(A,B,C,D,E,F,G,H,I)) => ((sumA(A,B,C,D,X,F,G,H,I)))))).
fof(sumA_EqSub_5,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(F,X) & sumA(A,B,C,D,E,F,G,H,I)) => ((sumA(A,B,C,D,E,X,G,H,I)))))).
fof(sumA_EqSub_6,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(G,X) & sumA(A,B,C,D,E,F,G,H,I)) => ((sumA(A,B,C,D,E,F,X,H,I)))))).
fof(sumA_EqSub_7,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(H,X) & sumA(A,B,C,D,E,F,G,H,I)) => ((sumA(A,B,C,D,E,F,G,X,I)))))).
fof(sumA_EqSub_8,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(I,X) & sumA(A,B,C,D,E,F,G,H,I)) => ((sumA(A,B,C,D,E,F,G,H,X)))))).
fof(nsumA_EqSub_0,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(A,X) & nsumA(A,B,C,D,E,F,G,H,I)) => ((nsumA(X,B,C,D,E,F,G,H,I)))))).
fof(nsumA_EqSub_1,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(B,X) & nsumA(A,B,C,D,E,F,G,H,I)) => ((nsumA(A,X,C,D,E,F,G,H,I)))))).
fof(nsumA_EqSub_2,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(C,X) & nsumA(A,B,C,D,E,F,G,H,I)) => ((nsumA(A,B,X,D,E,F,G,H,I)))))).
fof(nsumA_EqSub_3,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(D,X) & nsumA(A,B,C,D,E,F,G,H,I)) => ((nsumA(A,B,C,X,E,F,G,H,I)))))).
fof(nsumA_EqSub_4,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(E,X) & nsumA(A,B,C,D,E,F,G,H,I)) => ((nsumA(A,B,C,D,X,F,G,H,I)))))).
fof(nsumA_EqSub_5,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(F,X) & nsumA(A,B,C,D,E,F,G,H,I)) => ((nsumA(A,B,C,D,E,X,G,H,I)))))).
fof(nsumA_EqSub_6,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(G,X) & nsumA(A,B,C,D,E,F,G,H,I)) => ((nsumA(A,B,C,D,E,F,X,H,I)))))).
fof(nsumA_EqSub_7,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(H,X) & nsumA(A,B,C,D,E,F,G,H,I)) => ((nsumA(A,B,C,D,E,F,G,X,I)))))).
fof(nsumA_EqSub_8,axiom, (! [A,B,C,D,E,F,G,H,I,X] : ((eq(I,X) & nsumA(A,B,C,D,E,F,G,H,I)) => ((nsumA(A,B,C,D,E,F,G,H,X)))))).
fof(proposition_17,conjecture,(  ! [A,B,C] : ((triangle(A,B,C)) => ? [X,Y,Z] : (sumA(A,B,C,B,C,A,X,Y,Z))))).
