fof(ax1, axiom,! [X] : (p1(X) => p2(X)) ).
fof(ax2, axiom,! [X] : (p2(X) => p3(X)) ).
fof(ax3, axiom,! [X] : (p3(X) => p4(X)) ).
fof(ax4, axiom,! [X] : (p4(X) => p5(X)) ).
fof(ax5, axiom,! [X] : (p5(X) => p6(X)) ).
fof(ax6, axiom,! [X] : (p6(X) => p7(X)) ).
fof(ax7, axiom,! [X] : (p7(X) => p8(X)) ).
fof(ax8, axiom,! [X] : (p8(X) => p9(X)) ).
fof(ax9, axiom,! [X] : (p9(X) => p10(X)) ).
fof(ax9, axiom,! [X] : (p10(X) => p11(X)) ).
fof(disjingoal,conjecture, ! [Z] : (p1(Z) => p11(Z))).
